### ISSUE TITLE
`-Xgen-mixin-forwarders` crashes for default methods

### ISSUE THREAD

**Issue by lrytz** [scala/scala-dev#210]
``` scala
trait O[T] extends java.util.Comparator[T] // Comparator has a method `default Comparator<T> reversed`

class C extends O[String] {
  def compare(a: String, b: String) = 0
}
```

crashes the compiler with `-Xgen-mixin-forwarders`:

```
java.lang.AssertionError: assertion failed:
  cannot invokespecial java/util/Comparator.reversed, the interface is not a direct parent.

        at scala.tools.nsc.Global.assert(Global.scala:229)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genCallMethod(BCodeBodyBuilder.scala:1089)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genApply(BCodeBodyBuilder.scala:584)
        at scala.tools.nsc.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:298)
        at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.emitNormalMethodBody$1(BCodeSkelBuilder.scala:604)
        at scala.tools.nsc.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genDefDef(BCodeSkelBuilder.scala:636)
```

**Comment by lrytz** [comment]
maybe something to fix for RC1..?

**Comment by lrytz** [comment]
For reference: in M4 we add the interface as a direct parent during code gen when emitting a super call to a default method: https://github.com/scala/scala/blob/v2.12.0-M4/src/compiler/scala/tools/nsc/backend/jvm/BCodeBodyBuilder.scala#L1083-L1084

In a later commit this information ("late interfaces") was also encoded in the ClassBType: https://github.com/scala/scala/commit/3fca034

All of this was removed (for M5) when we changed the encoding to emit static methods for trait methods, super calls would directly target the static method (https://github.com/scala/scala/commit/7d51b3f).  A super call to a java-defined default method is now only allowed if the interface is a direct parent, this is checked during Mixins (https://github.com/scala/scala/commit/7d51b3f#diff-8b2a191e6261b31a9a6462e4a01d3b9cR351).

The `-Xgen-mixin-forwarders` flag was added in (https://github.com/scala/scala/commit/a0590aa), and it does its job also for inherited default methods. If the interface is not a direct parent of the class, an assertion in the backend will trigger the crash.

**Comment by lrytz** [comment]
Here's an example that crashes without the `-Xgen-mixin-forwarders` flag:

A.java:

``` java
interface A {
  default int m() { return 1; }
}
```

Test.scala

``` scala
class B extends A { override def m = 2 }
trait T extends A
class C extends B with T {
  override def m = super[T].m // should invoke A.m
}
```

The `super[T].m` invocation is translated to `invokespecial A.m`. This causes the assertion error in the backend: A is not a direct parent of C.

To translate the static binding `super[T].m`, the compiler checks the owner of `T.m`, which is `A`. If `A` was a trait (written in Scala), the call would be translated to `invokestatic A.m$`. But the static method doesn't exist (A is written in Java), so the call is translated to `invokespecial A.m`.

This example is the same as in https://github.com/scala/scala-dev/issues/143#issuecomment-232446342 but with of a Java-defined interface A instead of a superclass A. In this case, there also isn't a static method `A.m$`, so the call is translated to `invokespecial A.m`, which does not crash the backend (A is a class, the `invokespecial` is valid), but will resolve to `B.m` at runtime.

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/5369
