### ISSUE TITLE
unfork ScalaTest

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#230]
in order to get ScalaTest 3.0 building in the Scala 2.12 community build, I had to change its build as follows: https://github.com/SethTisue/scalatest/commit/f620c113b58efbf390d7601ac4ace9af3dd63662

because I had to fork ScalaTest to get this change in, the community build is no longer tracking the head of the 3.0.x branch

**Comment by SethTisue** [comment]
iirc the problem had to do with needing to disable Scala.js support.

to demonstrate the problem to Bill and Chua I need a test run log to show them. the old runs were a hole ago, so I made a new unfork-scalatest branch and started this test run (404 right now): https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/602/consoleFull

**Comment by SethTisue** [comment]
argh, I meant to open this in the scala/community-builds repo, but whatevs

**Comment by SethTisue** [comment]
here's the log of what dbuild complains about:

```
[scalatest] [info] Dependencies among subprojects:
[scalatest] [info] genEmptyTests -> scalatest,common-test,scalacticMacro
[scalatest] [info] genRegularTests1 -> scalatest,common-test,scalacticMacro
[scalatest] [info] scalacticJS -> scalacticMacroJS
[scalatest] [info] examples -> scalacticMacro,scalactic,scalatest
[scalatest] [info] scalactic -> scalacticMacro
[scalatest] [info] scalacticTestJS -> scalacticJS,scalatestJS,commonTestJS
[scalatest] [info] genMustMatchersTests2 -> scalatest,common-test,scalacticMacro
[scalatest] [info] genSortedTests -> scalatest,common-test,scalacticMacro
[scalatest] [info] genMustMatchersTests4 -> scalatest,common-test,scalacticMacro
[scalatest] [info] scalatestTestJS -> scalatestJS,commonTestJS
[scalatest] [info] scalatest -> scalacticMacro,scalactic
[scalatest] [info] genRegularTests2 -> scalatest,common-test,scalacticMacro
[scalatest] [info] scalatestAppJS -> scalacticMacroJS,scalacticJS,scalatestJS
[scalatest] [info] genMustMatchersTests3 -> scalatest,common-test,scalacticMacro
[scalatest] [info] genLoneElementTests -> scalatest,common-test,scalacticMacro
[scalatest] [info] common-test -> scalacticMacro,scalatest
[scalatest] [info] scalatestApp -> scalacticMacro,scalactic,scalatest
[scalatest] [info] genInspectorsTests -> scalatest,common-test,scalacticMacro
[scalatest] [info] commonTestJS -> scalacticMacroJS,scalatestJS
[scalatest] [info] genRegularTests4 -> scalatest,common-test,scalacticMacro
[scalatest] [info] scalatestJS -> scalacticMacroJS,scalacticJS
[scalatest] [info] genTheyTests -> scalatest,common-test,scalacticMacro
[scalatest] [info] scalacticMacro -> 
[scalatest] [info] genInspectorsShorthandsTests2 -> scalatest,common-test,scalacticMacro
[scalatest] [info] scalactic-test -> scalactic,scalatest,common-test
[scalatest] [info] examplesJS -> scalacticMacroJS,scalacticJS,scalatestJS
[scalatest] [info] genInspectorsShorthandsTests1 -> scalatest,common-test,scalacticMacro
[scalatest] [info] genRegularTests3 -> scalatest,common-test,scalacticMacro
[scalatest] [info] genMustMatchersTests1 -> scalatest,common-test,scalacticMacro
[scalatest] [info] genGenTests -> scalatest,common-test,scalacticMacro
[scalatest] [info] scalacticMacroJS -> 
[scalatest] [info] genContainTests1 -> scalatest,common-test,scalacticMacro
[scalatest] [info] genTablesTests -> scalatest,common-test,scalacticMacro
[scalatest] [info] genRegularTests5 -> scalatest,common-test,scalacticMacro
[scalatest] [info] genContainTests2 -> scalatest,common-test,scalacticMacro
[scalatest] [info] gentests -> 
[scalatest] [info] scalatest-test -> scalatest,common-test
[scalatest] [info] Aggregates of subprojects:
[scalatest] [info] genEmptyTests -> 
[scalatest] [info] genRegularTests1 -> 
[scalatest] [info] scalacticJS -> scalacticTestJS
[scalatest] [info] examples -> 
[scalatest] [info] scalactic -> scalactic-test
[scalatest] [info] scalacticTestJS -> 
[scalatest] [info] genMustMatchersTests2 -> 
[scalatest] [info] genSortedTests -> 
[scalatest] [info] genMustMatchersTests4 -> 
[scalatest] [info] scalatestTestJS -> 
[scalatest] [info] scalatest -> scalatest-test
[scalatest] [info] genRegularTests2 -> 
[scalatest] [info] scalatestAppJS -> scalacticJS,scalatestJS
[scalatest] [info] genMustMatchersTests3 -> 
[scalatest] [info] genLoneElementTests -> 
[scalatest] [info] common-test -> 
[scalatest] [info] scalatestApp -> scalactic,scalatest
[scalatest] [info] genInspectorsTests -> 
[scalatest] [info] commonTestJS -> 
[scalatest] [info] genRegularTests4 -> 
[scalatest] [info] scalatestJS -> scalatestTestJS
[scalatest] [info] genTheyTests -> 
[scalatest] [info] scalacticMacro -> 
[scalatest] [info] genInspectorsShorthandsTests2 -> 
[scalatest] [info] scalactic-test -> 
[scalatest] [info] examplesJS -> 
[scalatest] [info] genInspectorsShorthandsTests1 -> 
[scalatest] [info] genRegularTests3 -> 
[scalatest] [info] genMustMatchersTests1 -> 
[scalatest] [info] genGenTests -> 
[scalatest] [info] scalacticMacroJS -> 
[scalatest] [info] genContainTests1 -> 
[scalatest] [info] genTablesTests -> 
[scalatest] [info] genRegularTests5 -> 
[scalatest] [info] genContainTests2 -> 
[scalatest] [info] gentests -> genEmptyTests,genMustMatchersTests2,genSortedTests,genMustMatchersTests4,genMustMatchersTests3,genLoneElementTests,genInspectorsTests,genTheyTests,genInspectorsShorthandsTests2,genInspectorsShorthandsTests1,genMustMatchersTests1,genGenTests,genContainTests1,genTablesTests,genContainTests2
[scalatest] [info] scalatest-test -> 
[scalatest] [info] Building graph...
[scalatest] [info] sorting...
[scalatest:error] com.typesafe.dbuild.graph.CycleException: Cycle found
[scalatest:error]   at com.typesafe.dbuild.graph.Graph.checkCycles(Graphs.scala:90)
[scalatest:error]   at com.typesafe.dbuild.graph.Graph.safeTopological(Graphs.scala:95)
[scalatest:error]   at com.typesafe.dbuild.plugin.DependencyAnalysis$.printDependencies(DependencyAnalysis.scala:210)
```

@bvenners @cheeseng do you need those `aggregate` calls? without fully understanding your build, it's difficult for me to know if simply removing them might be an appropriate solution to suggest. those calls don't make sense to me — and it makes sense to me that they would result in dbuild complaining about a circular dependency. but maybe I just don't understand the intent behind them?

**Comment by SethTisue** [comment]
Bill has asked Chee Seng to look into it.

**Comment by cheeseng** [comment]
@SethTisue @bvenners the aggregations are for our convenient use, so that when we do sbt test it will be called on the aggregated test projects also.  Anyway, I have refactored the build a little to do the same thing: 

https://github.com/cheeseng/scalatest/commit/04485052677e824b19c596fba613356f4eb46847

It is in my branch here: 

https://github.com/cheeseng/scalatest/tree/build-aggregate-refactor

If it works for you, I can submit a PR to 3.1.x and 3.0.x (if needed).

Thanks.

**Comment by SethTisue** [comment]
let's try it: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/719/consoleFull (404 til Jenkins catches up)

**Comment by SethTisue** [comment]
```
[scalatest] [error] /home/jenkins/workspace/scala-2.12.x-integrate-community-build/target-0.9.5/project-builds/scalatest-8b66dc05468f0bcfea01a0a9ba2cffa30fabddef/scalatest/target/docsrc/src/main/scala/org/scalatest/selenium/WebBrowser.scala:4610: recursive value firefoxProfile needs type
[scalatest] [error]   implicit val webDriver = new FirefoxDriver(firefoxProfile)
[scalatest] [error]                                              ^
```

but extraction succeeded, so it looks like your branch just doesn't have the other recent commit that fixed the above error

so, I think the experiment was a success. yes please, merge this change into ScalaTest (and let me know, please, once it's on master)

**Comment by SethTisue** [comment]
P.S. for 3.0.x please — the 2.12 community build probably won't move to 3.1.x for a while yet

**Comment by cheeseng** [comment]
@SethTisue I submitted 2 PRs (one for 3.1.x and another for 3.0.x): 

https://github.com/scalatest/scalatest/pull/983
https://github.com/scalatest/scalatest/pull/984

Hopefully @bvenners will merge them in soon.

**Comment by bvenners** [comment]
I'm teaching today and will merge these in either tonight or tomorrow.
