### ISSUE TITLE
IncompatibleClassChangeError with lambdas in traits under the optimizer

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#242]
``` scala
trait Test {
  def test: Unit = {
    byName("".toString)
    ()
  }

  @inline
  final def byName(action: => Unit) = action
}

```

```
qscalac -opt:l:classpath -d /tmp sandbox/test.scala && javap -v -cp /tmp Test | cat -b | grep -i --color  '$anonfun$test$1'
    26    #17 = Utf8               $anonfun$test$1
    27    #18 = NameAndType        #17:#13        // $anonfun$test$1:()V
    28    #19 = Methodref          #2.#18         // Test.$anonfun$test$1:()V
    59    #50 = InterfaceMethodref #2.#18         // Test.$anonfun$test$1:()V
    60    #51 = MethodHandle       #6:#50         // invokestatic Test.$anonfun$test$1:()V
    97           0: invokestatic  #19                 // Method $anonfun$test$1:()V
   141    public static void $anonfun$test$1();
   170        #51 invokestatic Test.$anonfun$test$1:()V
```

**Comment by retronym** [comment]
Full bytecode: https://gist.github.com/retronym/f6285e1be6451bd384effe67ce9ba363

Minimized from:

```
⚡ java -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+128)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+128, mixed mode)

⚡ qscalac -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/lib/rt.jar:build/pack/lib/scala-library.jar sandbox/test.scala
Exception in thread "main" java.lang.IncompatibleClassChangeError: Method scala.util.PropertiesTrait.$anonfun$scalaProps$2(Ljava/io/InputStream;)V must be InterfaceMethodref constant
    at scala.util.PropertiesTrait.scalaProps(Properties.scala:46)
    at scala.util.PropertiesTrait.scalaProps$(Properties.scala:34)
```

**Comment by retronym** [comment]
Here's the spot that needs changing:

https://github.com/scala/scala/compare/2.12.x...retronym:ticket/242?expand=1

**Comment by lrytz** [comment]
This only fails on JDK 9 for me, same for you?

**Comment by lrytz** [comment]
Thanks for the patch, it was the correct thing to do.

**Comment by retronym** [comment]
Yep, it only fails on JDK9.
