### ISSUE TITLE
java.lang.NoSuchMethodError when running partest in clean build

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#258]
reported by @larsrh at https://gitter.im/typelevel/scala?at=581c9eed6cb7207630368687

**Comment by larsrh** [comment]
Also on Jira: [SI-10026](https://issues.scala-lang.org/browse/SI-10026)

**Comment by larsrh** [comment]
(Disregard the previous wrong link I posted, sorry.)

**Comment by larsrh** [comment]
I could reproduce it on another fresh checkout:

```
~/proj$ git clone github.com:scala/scala.git
Cloning into 'scala'...
remote: Counting objects: 341488, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 341488 (delta 3), reused 2 (delta 2), pack-reused 341481
Receiving objects: 100% (341488/341488), 78.26 MiB | 5.47 MiB/s, done.
Resolving deltas: 100% (232768/232768), done.
~/proj$ cd scala
~/proj/scala (2.12.x)$ git checkout v2.12.0-RC1
~/proj/scala ((v2.12.0-RC1))$ sbt
[info] Loading global plugins from /home/lars/.sbt/0.13/plugins/project
[info] Updating {file:/home/lars/.sbt/0.13/plugins/project/}global-plugins-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Loading global plugins from /home/lars/.sbt/0.13/plugins
[info] Updating {file:/home/lars/.sbt/0.13/plugins/}global-plugins...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Loading project definition from /home/lars/proj/scala/project/project
[info] Updating {file:/home/lars/proj/scala/project/project/}scala-build-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.                                                                                                                                                                                                                                                          
[info] Loading project definition from /home/lars/proj/scala/project                                                                                                                                                                                                           
[info] Updating {file:/home/lars/proj/scala/project/}scala-build...                                                                                                                                                                                                            
[info] Resolving net.virtual-void#sbt-dependency-graph;0.8.2 ...
[info] Updating {file:/home/lars/proj/scala/project/}scala-build...                                                                                                                                                                                                            
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] downloading https://repo1.maven.org/maven2/org/pantsbuild/jarjar/1.6.3/jarjar-1.6.3.jar ...                                                                                                                                                                             
[info]  [SUCCESSFUL ] org.pantsbuild#jarjar;1.6.3!jarjar.jar (178ms)                                                                                                                                                                                                           
[info] downloading https://repo1.maven.org/maven2/biz/aQute/bnd/biz.aQute.bnd/2.4.1/biz.aQute.bnd-2.4.1.jar ...                                                                                                                                                                
[info]  [SUCCESSFUL ] biz.aQute.bnd#biz.aQute.bnd;2.4.1!biz.aQute.bnd.jar (642ms)                                                                                                                                                                                              
[info] Done updating.                                                                                                                                                                                                                                                          
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.                                                                                                                                                                                                                                                          
[info] Compiling 14 Scala sources to /home/lars/proj/scala/project/target/scala-2.10/sbt-0.13/classes...                                                                                                                                                                       
[info] *** Welcome to the sbt build definition for Scala! ***                                                                                                                                                                                                                  
[info] Check README.md for more information.                                                                                                                                                                                                                                   
> partest --verbose test/files/pos/t2712-1.scala
[info] Updating {file:/home/lars/proj/scala/}partest-javaagent...                                                                                                                                                                                                              
[info] Updating {file:/home/lars/proj/scala/}library...                                                                                                                                                                                                                        
[info] Updating {file:/home/lars/proj/scala/}bootstrap...                                                                                                                                                                                                                      
[info] Resolving org.scala-lang.modules#scala-asm;5.1.0-scala-1 ...
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/modules/scala-asm/5.1.0-scala-1/scala-asm-5.1.0-scala-1.jar ...                                                                                                                                               
[info]  [SUCCESSFUL ] org.scala-lang.modules#scala-asm;5.1.0-scala-1!scala-asm.jar(bundle) (219ms)                                                                                                                                                                             
[info] Done updating.                                                                                                                                                                                                                                                          
[info] Done updating.                                                                                                                                                                                                                                                          
[info] Updating {file:/home/lars/proj/scala/}reflect...                                                                                                                                                                                                                        
[info] Resolving jline#jline;2.14.1 ...
[info] Done updating.
[info] Resolving org.scala-lang#scala-library;2.12.0-SNAPSHOT ...
[info] Done updating.
[info] Updating {file:/home/lars/proj/scala/}compiler...
[info] Resolving jline#jline;2.14.1 ...
[info] downloading https://repo1.maven.org/maven2/org/apache/ant/ant/1.9.4/ant-1.9.4.jar ...
[info]  [SUCCESSFUL ] org.apache.ant#ant;1.9.4!ant.jar (521ms)
[info] downloading https://repo1.maven.org/maven2/org/apache/ant/ant-launcher/1.9.4/ant-launcher-1.9.4.jar ...
[info]  [SUCCESSFUL ] org.apache.ant#ant-launcher;1.9.4!ant-launcher.jar (110ms)
[info] Done updating.
[info] Updating {file:/home/lars/proj/scala/}scaladoc...
[info] Updating {file:/home/lars/proj/scala/}scalap...
[info] Updating {file:/home/lars/proj/scala/}interactive...
[info] Resolving org.scala-lang.modules#scala-xml_2.12.0-M5;1.0.5 ...
[info] Done updating.
[info] Resolving org.scala-lang#scala-reflect;2.12.0-SNAPSHOT ...
[info] Updating {file:/home/lars/proj/scala/}repl...
[info] Resolving org.scala-sbt#test-interface;1.0 ...
[info] downloading https://repo1.maven.org/maven2/org/scala-lang/modules/scala-partest_2.12.0-M5/1.0.17/scala-partest_2.12.0-M5-1.0.17.jar ...
[info]  [SUCCESSFUL ] org.scala-lang.modules#scala-partest_2.12.0-M5;1.0.17!scala-partest_2.12.0-M5.jar (159ms)
[info] downloading https://repo1.maven.org/maven2/com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0.jar ...
[info]  [SUCCESSFUL ] com.googlecode.java-diff-utils#diffutils;1.3.0!diffutils.jar (111ms)
[info] Done updating.
[info] Resolving org.scala-lang.modules#scala-xml_2.12.0-M5;1.0.5 ...
[info] Done updating.
[info] Resolving org.scala-lang#scala-compiler-interactive;2.12.0-SNAPSHOT ...
[info] Done updating.
[info] Updating {file:/home/lars/proj/scala/}repl-jline...
[info] Resolving jline#jline;2.14.1 ...
[info] Done updating.
[info] Updating {file:/home/lars/proj/scala/}repl-jline-embedded...
[info] Resolving jline#jline;2.14.1 ...
[info] Done updating.
[info] Updating {file:/home/lars/proj/scala/}partest-extras...
[info] Resolving org.scala-sbt#test-interface;1.0 ...
[info] Done updating.
[info] Updating {file:/home/lars/proj/scala/}test...
[info] Resolving org.scala-lang.scala-sha-bootstrap.test.files.speclib#instrumented;1b11ac773055c1e942c6b5eb4aabdf02292a7194 ...
[info] downloading https://dl.bintray.com/typesafe/scala-sha-bootstrap/org/scala-lang/bootstrap/cd33e0a0ea249eb42363a2f8ba531186345ff68c/test/files/lib/nest.jar ...
[info]  [SUCCESSFUL ] org.scala-lang.scala-sha-bootstrap.test.files.lib#nest;cd33e0a0ea249eb42363a2f8ba531186345ff68c!nest.jar (208ms)
[info] downloading https://dl.bintray.com/typesafe/scala-sha-bootstrap/org/scala-lang/bootstrap/346d3dff4088839d6b4d163efa2892124039d216/test/files/lib/jsoup-1.3.1.jar ...
[info]  [SUCCESSFUL ] org.scala-lang.scala-sha-bootstrap.test.files.lib#jsoup-1.3.1;346d3dff4088839d6b4d163efa2892124039d216!jsoup-1.3.1.jar (357ms)
[info] downloading https://dl.bintray.com/typesafe/scala-sha-bootstrap/org/scala-lang/bootstrap/3794ec22d9b27f2b179bd34e9b46db771b934ec3/test/files/lib/macro210.jar ...
[info]  [SUCCESSFUL ] org.scala-lang.scala-sha-bootstrap.test.files.lib#macro210;3794ec22d9b27f2b179bd34e9b46db771b934ec3!macro210.jar (193ms)
[info] downloading https://dl.bintray.com/typesafe/scala-sha-bootstrap/org/scala-lang/bootstrap/981392dbd1f727b152cd1c908c5fce60ad9d07f7/test/files/lib/enums.jar ...
[info]  [SUCCESSFUL ] org.scala-lang.scala-sha-bootstrap.test.files.lib#enums;981392dbd1f727b152cd1c908c5fce60ad9d07f7!enums.jar (202ms)
[info] downloading https://dl.bintray.com/typesafe/scala-sha-bootstrap/org/scala-lang/bootstrap/b1ec8a095cec4902b3609d74d274c04365c59c04/test/files/lib/genericNest.jar ...
[info]  [SUCCESSFUL ] org.scala-lang.scala-sha-bootstrap.test.files.lib#genericNest;b1ec8a095cec4902b3609d74d274c04365c59c04!genericNest.jar (189ms)
[info] downloading https://dl.bintray.com/typesafe/scala-sha-bootstrap/org/scala-lang/bootstrap/02fe2ed93766323a13f22c7a7e2ecdcd84259b6c/test/files/lib/annotations.jar ...
[info]  [SUCCESSFUL ] org.scala-lang.scala-sha-bootstrap.test.files.lib#annotations;02fe2ed93766323a13f22c7a7e2ecdcd84259b6c!annotations.jar (190ms)
[info] downloading https://dl.bintray.com/typesafe/scala-sha-bootstrap/org/scala-lang/bootstrap/be8454d5e7751b063ade201c225dcedefd252775/test/files/lib/methvsfield.jar ...
[info]  [SUCCESSFUL ] org.scala-lang.scala-sha-bootstrap.test.files.lib#methvsfield;be8454d5e7751b063ade201c225dcedefd252775!methvsfield.jar (185ms)
[info] downloading https://dl.bintray.com/typesafe/scala-sha-bootstrap/org/scala-lang/bootstrap/e737b123d31eede5594ceda07caafed1673ec472/test/files/codelib/code.jar ...
[info]  [SUCCESSFUL ] org.scala-lang.scala-sha-bootstrap.test.files.codelib#code;e737b123d31eede5594ceda07caafed1673ec472!code.jar (189ms)
[info] downloading https://dl.bintray.com/typesafe/scala-sha-bootstrap/org/scala-lang/bootstrap/1b11ac773055c1e942c6b5eb4aabdf02292a7194/test/files/speclib/instrumented.jar ...
[info]  [SUCCESSFUL ] org.scala-lang.scala-sha-bootstrap.test.files.speclib#instrumented;1b11ac773055c1e942c6b5eb4aabdf02292a7194!instrumented.jar (207ms)
[info] Done updating.
[info] Compiling 3 Java sources to /home/lars/proj/scala/build/quick/classes/partest-javaagent...
[info] Compiling 582 Scala sources and 120 Java sources to /home/lars/proj/scala/build/quick/classes/library...
[info] 'compiler-interface' not yet compiled for Scala 2.12.0-M5. Compiling...
[info] Packaging /home/lars/proj/scala/build/pack/lib/scala-partest-javaagent.jar ...
[info] Done packaging.
[info]   Compilation completed in 11.571 s
[warn] there were 38 deprecation warnings (since 2.10.0)
[warn] there were 25 deprecation warnings (since 2.11.0)
[warn] there were 45 deprecation warnings (since 2.12.0)
[warn] there were 108 deprecation warnings in total; re-run with -deprecation for details
[warn] four warnings found
[info] Compiling 157 Scala sources to /home/lars/proj/scala/build/quick/classes/reflect...
[warn] there were three deprecation warnings (since 2.10.0)
[warn] there were four deprecation warnings (since 2.10.1)
[warn] there were 17 deprecation warnings (since 2.11.0)
[warn] there were two deprecation warnings (since 2.12.0)
[warn] there were 26 deprecation warnings in total; re-run with -deprecation for details
[warn] there were three unchecked warnings; re-run with -unchecked for details
[warn] 6 warnings found
[info] Compiling 292 Scala sources to /home/lars/proj/scala/build/quick/classes/compiler...
[warn] /home/lars/proj/scala/src/compiler/scala/tools/nsc/settings/ScalaSettings.scala:42: patterns after a variable pattern cannot match (SLS 8.1.1)
[warn]   private def multihelp = allSettings exists { case s => s.isHelping case _ => false }
[warn]                                                     ^
[warn] /home/lars/proj/scala/src/compiler/scala/tools/nsc/settings/ScalaSettings.scala:42: unreachable code due to variable pattern 's' on line 42
[warn]   private def multihelp = allSettings exists { case s => s.isHelping case _ => false }
[warn]                                                                                ^
[warn] there were 12 deprecation warnings (since 2.10.0)
[warn] there were 50 deprecation warnings (since 2.11.0)
[warn] there were three deprecation warnings (since 2.11.2)
[warn] there were 9 deprecation warnings (since 2.12.0)
[warn] there were 74 deprecation warnings in total; re-run with -deprecation for details
[warn] there were 32 unchecked warnings; re-run with -unchecked for details
[warn] there were three feature warnings; re-run with -feature for details
[warn] 9 warnings found
[info] Compiling 46 Scala sources to /home/lars/proj/scala/build/quick/classes/scaladoc...
[info] Compiling 23 Scala sources to /home/lars/proj/scala/build/quick/classes/scalap...
[info] Compiling 28 Scala sources to /home/lars/proj/scala/build/quick/classes/interactive...
[warn] there were four deprecation warnings (since 2.11.0)
[warn] there was one deprecation warning (since 2.12.0)
[warn] there were 5 deprecation warnings in total; re-run with -deprecation for details
[warn] there were two unchecked warnings; re-run with -unchecked for details
[warn] four warnings found
[info] Compiling 43 Scala sources and 1 Java source to /home/lars/proj/scala/build/quick/classes/repl...
[warn] there were two unchecked warnings; re-run with -unchecked for details
[warn] one warning found
[warn] there were 11 deprecation warnings (since 2.11.0)
[warn] there was one deprecation warning (since 2.12.0)
[warn] there were 12 deprecation warnings in total; re-run with -deprecation for details
[warn] three warnings found
[info] Compiling 4 Scala sources to /home/lars/proj/scala/build/quick/classes/repl-jline...
[info] Compiling 25 Scala sources and 1 Java source to /home/lars/proj/scala/build/quick/classes/partest-extras...
[warn] there was one deprecation warning (since 1.11.4)
[warn] there was one deprecation warning (since 2.12.0)
[warn] there were two deprecation warnings in total; re-run with -deprecation for details
[warn] there were 41 feature warnings; re-run with -feature for details
[warn] four warnings found
[error] Uncaught exception when running tests: java.lang.NoSuchMethodError: scala.Predef$._refArrayOps([Ljava/lang/Object;)[Ljava/lang/Object;
[trace] Stack trace suppressed: run last test/it:testOnly for the full output.
Exception in thread "Thread-29" java.io.EOFException
        at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2626)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1321)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
        at sbt.React.react(ForkTests.scala:114)
        at sbt.ForkTests$$anonfun$mainTestTask$1$Acceptor$2$.run(ForkTests.scala:74)
        at java.lang.Thread.run(Thread.java:745)
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for test/it:testOnly
[success] Total time: 210 s, completed 04.11.2016 19:31:18
```

**Comment by larsrh** [comment]
It doesn't happen if I don't check out a tag and use the `2.12.x` branch instead. Could a detached HEAD be the reason?

**Comment by SethTisue** [comment]
ah, you started with `git checkout v2.12.0-RC1`, yes, that's the crucial piece of information here. I think this is just a dupe of https://github.com/scala/scala-dev/issues/208

it's unfortunate that we ended up with a tagged release with this problem, but at least it was just an RC :-\

**Comment by SethTisue** [comment]
see also discussion at https://github.com/scala/scala/pull/5381. fyi @milessabin, who is ~~always ragging on us about~~ er, I mean, attentive to these issues :-)

**Comment by larsrh** [comment]
Ah, sorry, that was completely non-obvious to me. I tried googling for the stack trace but couldn't find anything. The reason I checked out the tag was that I was trying to figure out where [SI-10026](https://issues.scala-lang.org/browse/SI-10026) regressed.

**Comment by SethTisue** [comment]
no worries, it was a totally reasonable expectation that a tagged version should build
