### ISSUE TITLE
SI-9915 test not passing on Windows

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#262]
at e.g. https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-windows/407/consoleFull we see:

```
!! 1667 - run/t9915                                 [compilation failed]
##### Log file 'Y:\jenkins\workspace\scala-2.12.x-integrate-windows\test\files\run\t9915-run.log' from failed test #####
```

@som-snytt can you see if this is because https://github.com/scala/scala/pull/5384 was merged...?

**Comment by som-snytt** [comment]
@SethTisue You know breaking Windows builds is my favorite pastime.

**Comment by som-snytt** [comment]
There's also an encoding failure trying to display the log file. I don't suppose @SethTisue you could post the `-run.log` file here? Or can I retrieve the artifact?

IIUC, `partest.codec` means slurping is always UTF8. That means the log is differently encoded.

I wonder if the test source file is checked out on windows as UTF-8?

```
[error] Uncaught exception when running partest: java.util.concurrent.ExecutionException: java.nio.charset.MalformedInputException: Input length = 1
Picked up _JAVA_OPTIONS: -Duser.home=y:\jenkins
sbt.ForkMain$ForkError: java.util.concurrent.ExecutionException: java.nio.charset.MalformedInputException: Input length = 1
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at scala.tools.partest.nest.SuiteRunner.$anonfun$runTestsForFiles$5(Runner.scala:842)
    at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:193)
    at scala.collection.TraversableLike.map$(TraversableLike.scala:234)
    at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:193)
    at scala.tools.partest.nest.SuiteRunner.runTestsForFiles(Runner.scala:842)
    at scala.tools.partest.nest.AbstractRunner.$anonfun$run$16(AbstractRunner.scala:176)
    at scala.tools.partest.nest.AbstractRunner.$anonfun$run$16$adapted(AbstractRunner.scala:172)
    at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
    at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:193)
    at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
    at scala.tools.partest.nest.AbstractRunner.$anonfun$run$14(AbstractRunner.scala:172)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
    at scala.tools.partest.package$.timed(package.scala:129)
    at scala.tools.partest.nest.AbstractRunner.run(AbstractRunner.scala:172)
    at scala.tools.partest.sbt.PartestTask.execute(Framework.scala:43)
    at sbt.ForkMain$Run$2.call(ForkMain.java:296)
    at sbt.ForkMain$Run$2.call(ForkMain.java:286)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: sbt.ForkMain$ForkError: java.nio.charset.MalformedInputException: Input length = 1
    at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.BufferedReader.read1(BufferedReader.java:210)
    at java.io.BufferedReader.read(BufferedReader.java:286)
    at java.io.Reader.read(Reader.java:140)
    at scala.io.BufferedSource.mkString(BufferedSource.scala:94)
    at scala.reflect.io.File.slurp(File.scala:46)
    at scala.reflect.io.File.slurp(File.scala:46)
    at scala.tools.partest.package$FileOps.fileContents(package.scala:83)
    at scala.tools.partest.nest.NestUI.showLog$1(NestUI.scala:82)
    at scala.tools.partest.nest.NestUI.reportTest(NestUI.scala:93)
    at scala.tools.partest.nest.SuiteRunner.runTest(Runner.scala:825)
    at scala.tools.partest.nest.SuiteRunner.$anonfun$runTestsForFiles$2(Runner.scala:836)
    at scala.tools.partest.package$$anon$2.call(package.scala:135)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by SethTisue** [comment]
> I don't suppose @SethTisue you could post the -run.log file here?

(note to self: retrieved with `scp -i ~/.ssh/jenkins_id_rsa jenkins-worker-windows-publish:~jenkins/workspace/scala-2.12.x-integrate-windows/test/files/run/t9915-run.log ~/Desktop`)

[t9915-run.log.zip](https://github.com/scala/scala-dev/files/593305/t9915-run.log.zip)

buncha `unmappable character for encoding Cp1252` errors

**Comment by SethTisue** [comment]
(it would be nice if partest failure logs became Jenkins artifacts...)

**Comment by som-snytt** [comment]
OK, so javac is using Cp1252. I'll recall how to set -encoding under partest.

**Comment by SethTisue** [comment]
pretty sure if you enter Cp1252 into your TI calculator and turn it upside down it spells something rude.

**Comment by SethTisue** [comment]
continuing on https://github.com/scala/scala/pull/5533
