### ISSUE TITLE
CLA checker won't sign off on Som's PR #5546

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#270]
Scabot's in a @som-snytt snit at https://github.com/scala/scala/pull/5546

autocorrect substituted “Somme” for “Som". pretty sure a Somme Snytte came over on the Mayflower?

**Comment by SethTisue** [comment]
let's see what the Scabot logs have to say

```
[INFO] [11/19/2016 06:47:22.118] [application-akka.actor.default-dispatcher-17527] [ActorSystem(application)] Processing PullRequestEvent(opened,5546,scala/scala#5546) for scala/scala
[INFO] [11/19/2016 06:47:22.119] [application-akka.actor.default-dispatcher-17527] [akka://application/user/github/scala-scala/5546] PR open --> scala/scala#5546
[INFO] [11/19/2016 06:47:22.884] [application-akka.actor.default-dispatcher-17532] [akka://application/user/github/scala-scala/5546] Launched scala-2.12.x-validate-main for 0c147ec1d4849d4d886f1236293eceb6f4593b3c: 
[ESC[31merrorESC[0m] p.c.s.n.PlayDefaultUpstreamHandler - Cannot invoke the action
scala.MatchError: issues (of class java.lang.String)
        at controllers.Scabot$$anonfun$github$1$$anonfun$1.apply(Scabot.scala:44) ~[com.lightbend.gui-0.1.0.jar:0.1.0]
        at controllers.Scabot$$anonfun$github$1$$anonfun$1.apply(Scabot.scala:44) ~[com.lightbend.gui-0.1.0.jar:0.1.0]
        at scala.Option.map(Option.scala:146) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at controllers.Scabot$$anonfun$github$1.apply(Scabot.scala:44) ~[com.lightbend.gui-0.1.0.jar:0.1.0]
        at controllers.Scabot$$anonfun$github$1.apply(Scabot.scala:43) ~[com.lightbend.gui-0.1.0.jar:0.1.0]
        at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408) ~[com.typesafe.play.play_2.11-2.4.0.jar:2.4.0]
        at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407) ~[com.typesafe.play.play_2.11-2.4.0.jar:2.4.0]
        at play.api.mvc.Action$.invokeBlock(Action.scala:533) ~[com.typesafe.play.play_2.11-2.4.0.jar:2.4.0]
        at play.api.mvc.Action$.invokeBlock(Action.scala:530) ~[com.typesafe.play.play_2.11-2.4.0.jar:2.4.0]
        at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493) ~[com.typesafe.play.play_2.11-2.4.0.jar:2.4.0]
[ESC[31merrorESC[0m] application - 

! @725bl5ian - Internal server error, for (POST) [/github] ->
 
play.api.UnexpectedException: Unexpected exception[MatchError: issues (of class java.lang.String)]
        at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:250) ~[com.typesafe.play.play_2.11-2.4.0.jar:2.4.0]
        at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:180) ~[com.typesafe.play.play_2.11-2.4.0.jar:2.4.0]
        at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [com.typesafe.play.play_2.11-2.4.0.jar:2.4.0]
        at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [com.typesafe.play.play_2.11-2.4.0.jar:2.4.0]
        at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [com.typesafe.play.play_2.11-2.4.0.jar:2.4.0]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:273) [com.typesafe.play.play-netty-server_2.11-2.4.0.jar:2.4.0]
        at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$3.applyOrElse(PlayDefaultUpstreamHandler.scala:269) [com.typesafe.play.play-netty-server_2.11-2.4.0.jar:2.4.0]
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:344) [org.scala-lang.scala-library-2.11.7.jar:na]
        at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:343) [org.scala-lang.scala-library-2.11.7.jar:na]
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.11.7.jar:na]
Caused by: scala.MatchError: issues (of class java.lang.String)
        at controllers.Scabot$$anonfun$github$1$$anonfun$1.apply(Scabot.scala:44) ~[com.lightbend.gui-0.1.0.jar:0.1.0]
        at controllers.Scabot$$anonfun$github$1$$anonfun$1.apply(Scabot.scala:44) ~[com.lightbend.gui-0.1.0.jar:0.1.0]
        at scala.Option.map(Option.scala:146) ~[org.scala-lang.scala-library-2.11.7.jar:na]
        at controllers.Scabot$$anonfun$github$1.apply(Scabot.scala:44) ~[com.lightbend.gui-0.1.0.jar:0.1.0]
        at controllers.Scabot$$anonfun$github$1.apply(Scabot.scala:43) ~[com.lightbend.gui-0.1.0.jar:0.1.0]
        at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408) ~[com.typesafe.play.play_2.11-2.4.0.jar:2.4.0]
        at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407) ~[com.typesafe.play.play_2.11-2.4.0.jar:2.4.0]
        at play.api.mvc.Action$.invokeBlock(Action.scala:533) ~[com.typesafe.play.play_2.11-2.4.0.jar:2.4.0]
        at play.api.mvc.Action$.invokeBlock(Action.scala:530) ~[com.typesafe.play.play_2.11-2.4.0.jar:2.4.0]
        at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493) ~[com.typesafe.play.play_2.11-2.4.0.jar:2.4.0]
```

**Comment by SethTisue** [comment]
https://www.lightbend.com/contribute/cla/scala/check/som-snytt seems to be as expected:

```json
{"user":"som-snytt","signed":true,"version":"1.0","currentVersion":"1.0"}
```

**Comment by SethTisue** [comment]
I added a hook to Scabot's CLI so we can do the CLA check locally:

```
scala> val c = new scabot.cli.CLI("scala")
c: scabot.cli.CLI = scabot.cli.CLI@36f2db99

scala> c.await(c.lightbend.checkCla("som-snytt"))
res0: (c.CLARecord, spray.http.StatusCode) = (CLARecord(som-snytt,true,Some(1.0),1.0),200 OK)
```

everything seems in order there.

**Comment by SethTisue** [comment]
I guess this must be going wrong in Actors.scala:

```scala
      for {
        pending   <- githubApi.postStatus(last, claStatus(None, user, claKind, checkUrl, signUrl))
        claRecord <- checkCla
        res       <- githubApi.postStatus(last, claStatus(Some(claRecord.signed), user, claKind, checkUrl, signUrl))
      } yield res
```

two possible debugging paths:

* try to get the actor system running locally
* add more logging, then try again in production and see what the logs say

@adriaanm do you think this is even worth pursuing? I'm going to assume it's not unless we start seeing this more often. let's just `/nothingtoseehere` it and move on
