### ISSUE TITLE
Error in CI: error when running tests: sbt.ForkMain$Run$RunAborted: java.net.SocketException: Broken pipe (Write failed)

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#277]
https://scala-ci.typesafe.com/job/scala-2.12.x-validate-test/3717/consoleFull

```
ok 42 - presentation/visibility                 
ok 43 - presentation/t8941b                     
ok 44 - presentation/memory-leaks               

Internal error when running tests: sbt.ForkMain$Run$RunAborted: java.net.SocketException: Broken pipe (Write failed)
[error] Error: Total 0, Failed 0, Errors 0, Passed 0
[error] Error during tests:
[error] 	Forked test harness failed: java.lang.NullPointerException
[error] 	at sbt.TestEvent$$anonfun$overallResult$1.apply(TestReportListener.scala:72)
[error] 	at sbt.TestEvent$$anonfun$overallResult$1.apply(TestReportListener.scala:71)
[error] 	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:51)
[error] 	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:60)
[error] 	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:34)
[error] 	at scala.collection.TraversableOnce$class./:(TraversableOnce.scala:138)
[error] 	at scala.collection.AbstractTraversable./:(Traversable.scala:105)
[error] 	at sbt.TestEvent$.overallResult(TestReportListener.scala:71)
[error] 	at sbt.TestEvent$$anon$1.<init>(TestReportListener.scala:66)
[error] 	at sbt.TestEvent$.apply(TestReportListener.scala:65)
[error] 	at sbt.React.react(ForkTests.scala:137)
[error] 	at sbt.ForkTests$$anonfun$mainTestTask$1$Acceptor$2$.run(ForkTests.scala:76)
[error] 	at java.lang.Thread.run(Thread.java:745)
Partest version:     
Compiler under test: $baseDir/compiler
```

Spurious? Known issue? Worth a look before 2.12.1

**Comment by SethTisue** [comment]
seen again: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-bootstrap/688/consoleFull

**Comment by SethTisue** [comment]
another one https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-bootstrap/143/consoleFull

**Comment by SethTisue** [comment]
can't recall having seen this in a long time.
