### ISSUE TITLE
intermittent failure: scala.sys.process.PipeSourceSinkTest.runloopInterrupted (JUnit test)

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#313]
seen at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-windows/525/consoleFull:

```
[error] Test scala.sys.process.PipeSourceSinkTest.runloopInterrupted failed: java.util.concurrent.TimeoutException: Futures timed out after [1 second], took 1.046 sec
[error]     at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
[error]     at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:259)
[error]     at scala.concurrent.Await$.$anonfun$result$1(package.scala:190)
[error]     at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[error]     at scala.concurrent.Await$.result(package.scala:123)
[error]     at scala.sys.process.PipeSourceSinkTest.runloopInterrupted(PipedProcessTest.scala:293)
[error]     ...
```

just needs a little longer timeout, looks like.

**Comment by SethTisue** [comment]
also seen at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-windows/522/consoleFull, so, not utterly rare

**Comment by som-snytt** [comment]
```
// Each test normally ends in a moment
```
Maybe it says a moment, but the API expects a long value in millimoments.
