### ISSUE TITLE
scala-js and http4s failing in 2.12.x community build (NPE in ErasureTransformer)

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#314]
from https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1278/consoleFull:

```
[scala-js] [error] error: java.lang.NullPointerException
[scala-js] [error] 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.preEraseApply(Erasure.scala:1077)
[scala-js] [error] 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.preErase(Erasure.scala:1121)
[scala-js] [error] 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:1201)
[scala-js] [error] 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:936)
```

and

```
java.lang.NullPointerException
[http4s] 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.preEraseApply(Erasure.scala:1077)
[http4s] 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.preErase(Erasure.scala:1121)
[http4s] 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:1201)
[http4s] 	at scala.tools.nsc.transform.Erasure$ErasureTransformer$$anon$1.transform(Erasure.scala:936)
[http4s] 	at scala.reflect.internal.Trees.itransform
```

not intermittent, same failures also seen in other recent builds

**Comment by SethTisue** [comment]
last build where these projects were green was https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1276/ at scala/scala@13f7b2a, first failure at scala/scala@effde0c

```
*   effde0cd2c - Merge pull request #5726 from scala/revert-5629-issue/10120-quote-err (24 hours ago) <Adriaan Moors>
|\  
| * d60f6e3407 - (origin/revert-5629-issue/10120-quote-err, origin/pull/5726) Revert "SI-10133 Require escaped single quote char lit" (28 hours ago) <Adriaan Moors>
|/  
*   a8c4a54d18 - Merge pull request #5663 from gourlaysama/ticket/sd-256-enable-repl-colors-unix-2 (28 hours ago) <Adriaan Moors>
|\  
| * 6411170ede - (origin/pull/5663) SD-256 enable colored output by default on unix (33 hours ago) <Antoine Gourlay>
* |   c96a977989 - Merge pull request #5658 from retronym/topic/hashhash (33 hours ago) <Lukas Rytz>
|\ \  
| |/  
|/|   
| * f85c62e33e - (retronym/topic/hashhash, origin/pull/5658) Fix erasure of the qualifier of ## (4 weeks ago) <Jason Zaugg>
*   76bfb9e0e5 - Merge pull request #5708 from szeiger/issue/si10194 (34 hours ago) <Lukas Rytz>
|\  
| * 1d22ee4ba3 - (origin/pull/5708) SI-10194: Fix abstract type resolution for overloaded HOFs (2 days ago) <Stefan Zeiger>
*   dabec1a262 - Merge pull request #5700 from retronym/ticket/10154-refactor (2 days ago) <Lukas Rytz>
|\  
| * 06eee798f5 - (origin/pull/5700) Refactor implementation of lookupCompanion (4 days ago) <Jason Zaugg>
* 2f1e0c22ec - Merge pull request #5704 from som-snytt/issue/10190-elide-string (2 days ago) <Lukas Rytz>
* 6fb382501f - (origin/pull/5704) SI-10190 Elide string to empty instead of null (7 days ago) <Som Snytt>
```

**Comment by SethTisue** [comment]
team: should I bisect further, or is it already obvious which of the six PR's might be the culprit?

**Comment by adriaanm** [comment]
I'd guess the more eager call to `preErase` may be revealing an underlying bug: https://github.com/scala/scala/pull/5658/files#diff-34082ec02c067748f0d47c0bf037a717R1063
