### ISSUE TITLE
check osgi test log in 2.13 boostrap

### ISSUE THREAD

**Issue by lrytz** [scala/scala-dev#351]
There are some stack traces that are not around in 2.12

https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-bootstrap/306/consoleFull

```
[info] Test tools.test.osgi.BasicTest.everythingLoads started
org.osgi.framework.BundleException: Unable to resolve org.scala-lang.modules.scala-swing [13](R 13.0): missing requirement [org.scala-lang.modules.scala-swing [13](R 13.0)] osgi.wiring.package; (&(osgi.wiring.package=scala.collection.parallel)(version>=2.12.0)(!(version>=3.0.0))) Unresolved requirements: [[org.scala-lang.modules.scala-swing [13](R 13.0)] osgi.wiring.package; (&(osgi.wiring.package=scala.collection.parallel)(version>=2.12.0)(!(version>=3.0.0)))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4114)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2111)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1365)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
org.osgi.framework.BundleException: Unable to resolve org.scala-lang.modules.scala-xml [19](R 19.0): missing requirement [org.scala-lang.modules.scala-xml [19](R 19.0)] osgi.wiring.package; (&(osgi.wiring.package=scala.collection.parallel)(version>=2.12.0)(!(version>=3.0.0))) Unresolved requirements: [[org.scala-lang.modules.scala-xml [19](R 19.0)] osgi.wiring.package; (&(osgi.wiring.package=scala.collection.parallel)(version>=2.12.0)(!(version>=3.0.0)))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4114)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2111)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1365)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
[info] Test run finished: 0 failed, 0 ignored, 1 total, 0.218s
[info] Test run started
[info] Test tools.test.osgi.libonly.BasicLibraryTest.everythingLoads started
[info] Test run finished: 0 failed, 0 ignored, 1 total, 0.49s
[info] Test run started
[info] Test tools.test.osgi.reflection.toolbox.ReflectionToolBoxTest.basicMirrorThroughOsgi started
org.osgi.framework.BundleException: Unable to resolve org.scala-lang.modules.scala-swing [13](R 13.0): missing requirement [org.scala-lang.modules.scala-swing [13](R 13.0)] osgi.wiring.package; (&(osgi.wiring.package=scala.collection.parallel)(version>=2.12.0)(!(version>=3.0.0))) Unresolved requirements: [[org.scala-lang.modules.scala-swing [13](R 13.0)] osgi.wiring.package; (&(osgi.wiring.package=scala.collection.parallel)(version>=2.12.0)(!(version>=3.0.0)))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4114)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2111)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1365)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
org.osgi.framework.BundleException: Unable to resolve org.scala-lang.modules.scala-xml [19](R 19.0): missing requirement [org.scala-lang.modules.scala-xml [19](R 19.0)] osgi.wiring.package; (&(osgi.wiring.package=scala.collection.parallel)(version>=2.12.0)(!(version>=3.0.0))) Unresolved requirements: [[org.scala-lang.modules.scala-xml [19](R 19.0)] osgi.wiring.package; (&(osgi.wiring.package=scala.collection.parallel)(version>=2.12.0)(!(version>=3.0.0)))]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4114)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2111)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1365)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:745)
[info] Test run finished: 0 failed, 0 ignored, 1 total, 3.886s
```

**Comment by lrytz** [comment]
Maybe this is because the Scala build hard-codes the binary version to 2.12, see https://github.com/scala/scala/pull/5810.

I wonder if these are failures that should have failed the build.

**Comment by lrytz** [comment]
Fixed now, https://github.com/scala/scala/pull/5810 and https://github.com/scala/scala/pull/5790 did it
