### ISSUE TITLE
Scala syntax tree returned from inferImplicitValue is failing to evaluate

### ISSUE THREAD

**Issue by erikerlandson** [scala/scala-dev#353]
The tree returned from `inferImplicitValue` cannot (afaict) be evaluated using `c.eval` unless it was previously declared and compiled in a separate (sub)project.  I originally reported this problem on [stackoverflow](http://stackoverflow.com/questions/43097790/scala-syntax-tree-returned-from-inferimplicitvalue-is-failing-to-evaluate).

Consider the following simplified setup, where I define a method `foo` with a macro implementation `macroImpl`, which looks for an implicit declaration of type `DemoEvidence` and returns its value:

```scala
// a class for implicit evidence
class DemoEvidence(val value: Int)

// define 'foo' method for invoking the macro
object demoModule {
  def foo: Int = macro DemoMacros.fooImpl
}

class DemoMacros(val c: whitebox.Context) {
  import c.universe._

  def fooImpl: Tree = {
    val vInt = try {
      // get the tree representing the implicit value
      val impl = c.inferImplicitValue(typeOf[DemoEvidence], silent = false)
      // print it out
      println(s"impl= $impl")
      // try to evaluate the tree (this is failing)
      val eval = c.eval(c.Expr[DemoEvidence](c.untypecheck(impl.duplicate)))
      eval.value
    } catch {
      case e: Throwable => {
        // on failure print out the failure message
        println(s"Eval failed with: $e\nStack trace:\n${e.printStackTrace}")
        0
      }
    }
    q"$vInt"  // return tree representing the integer value
  }
}
```

If I compile the above, and then invoke it:
```scala
object demo {
  implicit val demoEvidence: DemoEvidence = new DemoEvidence(42)
  val i: Int = demoModule.foo
}
```

I see the compilation fail in the following way:

```scala
impl= demo.this.demoEvidence
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal$$anonfun$compile$1.apply(ToolBoxFactory.scala:275)
...
```

Full output at: https://gist.github.com/erikerlandson/df48f64329be6ab9de9caef5f5be4a83

You can see it is finding the tree for the declared implicit value demo.this.demoEvidence, but evaluation of that tree is failing.  If the implicit value is defined in a (sub)project, and compiled, and then used exterior to that project, the evaluation of the tree works as expected. 

I am not sure if this is a fundamental constraint that can't be changed, or something that could be fixed.

**Comment by erikerlandson** [comment]
I was hoping that inferImplicitValue would return a tree equivalent to q"new DemoEvidence(42)" inside the macro. In theory it seems like that should be available somewhere in the current macro context, at least assuming that lines of code are compiled in order.  Since it has `q"demo.this.demoEvidence"`, I assume it must also have `q"demo.this.demoEvidence = new DemoEvidence(42)"`, and therefore be able to infer q"new DemoEvidence(42)"

**Comment by erikerlandson** [comment]
It seems that there are two possible use cases.  The first one is the one that is currently implemented, where it returns the AST of the expression that implicit declaration would be replaced with after compilation.

The second one is one that I'm now interested in, where what I want is the AST of the value (as opposed to the AST of the implicit variable itself).  Currently, this value may be returned if the implicit is being generated by a function, but in other cases I just get the variable.

Is it possible to create a new variation of `inferImplicitValue` that **always** returns the AST of the value itself?
