### ISSUE TITLE
regression in 2.12.x on Windows: exception in ​anyval-box-types.scala

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#412]
first seen at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-windows/698/, every run since has failed with the same error

* Scala SHA for last green run: scala/scala@e12ac748cda072a42c67cfd0a0151947fc9c36e3
* Scala SHA for first red run: scala/scala@311a5760306f63d96b28c0a350d783297d0db672

PRs merged in between:
```
    Merge pull request #6008 from retronym/ticket/sd409
    Merge pull request #5991 from hrhino/bugfix/t10042
    Merge pull request #6017 from Philippus/issue-9423/fix-iterator-api-desc
    Merge pull request #5980 from retronym/ticket/sd-337-incoptions
    Merge pull request #5949 from hrhino/feature/opt-prim-instanceof
    Merge pull request #6024 from lrytz/t10439
```

**Comment by SethTisue** [comment]
the initial exception is actually

```
Caused by: sbt.ForkMain$ForkError: java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.read1(BufferedReader.java:210)
	at java.io.BufferedReader.read(BufferedReader.java:286)
	at java.io.Reader.read(Reader.java:140)
	at scala.io.BufferedSource.mkString(BufferedSource.scala:94)
	at scala.reflect.io.Streamable$Chars.slurp(Streamable.scala:120)
	at scala.reflect.io.Streamable$Chars.slurp$(Streamable.scala:118)
	at scala.reflect.io.File.slurp(File.scala:46)
	at scala.reflect.io.Streamable$Chars.slurp(Streamable.scala:117)
	at scala.reflect.io.Streamable$Chars.slurp$(Streamable.scala:117)
	at scala.reflect.io.File.slurp(File.scala:46)
	at scala.tools.partest.package$FileOps.fileContents(package.scala:83)
	at scala.tools.partest.package$FileOps.fileLines(package.scala:84)
	at scala.tools.partest.package$FileOps.mapInPlace(package.scala:62)
	at scala.tools.partest.nest.Runner.normalizeLog(Runner.scala:365)
	at scala.tools.partest.nest.Runner.diffIsOk(Runner.scala:375)
	at scala.tools.partest.nest.Runner.$anonfun$run$2(Runner.scala:655)
	at scala.tools.partest.nest.Runner.$anonfun$runTestCommon$1(Runner.scala:529)
	at scala.tools.partest.nest.Runner.runInContext(Runner.scala:415)
	at scala.tools.partest.nest.Runner.runTestCommon(Runner.scala:529)
	at scala.tools.partest.nest.Runner.run(Runner.scala:655)
	at scala.tools.partest.nest.SuiteRunner.$anonfun$runTest$1(Runner.scala:774)
	at scala.tools.partest.package$.timed(package.scala:129)
	at scala.tools.partest.nest.SuiteRunner.liftedTree1$1(Runner.scala:774)
	at scala.tools.partest.nest.SuiteRunner.runTest(Runner.scala:774)
	at scala.tools.partest.nest.SuiteRunner.$anonfun$runTestsForFiles$2(Runner.scala:789)
	at scala.tools.partest.package$$anon$2.call(package.scala:135)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by SethTisue** [comment]
@hrhino @lrytz @retronym I bet this has to do with https://github.com/scala/scala/pull/5949. who wants to look into it? it looks like partest is getting confused by non-ASCII characters in the test. it isn't clear to me whether there might be a real issue underneath, or whether it's just a partest phantom.

**Comment by hrhino** [comment]
@SethTisue yep, just confirmed. I can push up a commit that removes it (yikes) but I wonder what's causing `reflect.io.File` to choke.

I can ~steal~ borrow a windows box and see if I can make it non-choke tonight.

Sorry 'bout that...

**Comment by retronym** [comment]
Partest uses the default encoding [in](https://github.com/scala/scala-partest/blob/bd2d2c6c12d5a49aa9ec7eeb06f9e9c9d7928487/src/main/scala/scala/tools/partest/package.scala#L83):

```
def fileContents: String    = try sf.slurp() catch { case _: java.io.FileNotFoundException => "" }
```

Rather than explicitly passing `UTF-8` as the codec.

When it forks processes to run the compiled `run` tests, it explicitly [sets](https://github.com/scala/scala-partest/blob/1c263205b8e1b16458073814dc61888118905acb/src/main/scala/scala/tools/partest/nest/Runner.scala#L174) `-Dfile.encoding=UTF-8`.

The old `./test/partest` script (removed in https://github.com/scala/scala/commit/0bf343e000dd725933f8a08bcfd1c6fa700889b6) used to also set `-Dfile.encoding=UTF-8` to the top-level process in partest. We forgot to port this into the part of our SBT build that forks partest.

**Comment by retronym** [comment]
I've submitted a fix.
