### ISSUE TITLE
2.12.x-integrate-windows consistently failing in ZipAndJarFileLookupFactoryTest

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#427]
@retronym scala/scala@bcf47b165ccfd8e1827188f70aeb24e2cecfb80f seems like the likely culprit here?

example (from https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-windows/741/consoleFull):

```
[info] Test scala.tools.nsc.classpath.ZipAndJarFileLookupFactoryTest.cacheInvalidation started
[error] Test scala.tools.nsc.classpath.ZipAndJarFileLookupFactoryTest.cacheInvalidation failed: java.nio.file.FileSystemException: y:\jenkins\tmp\test-1435318257402903551.jar: The process cannot access the file because it is being used by another process.

[error] , took 0.064 sec
[error]     at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
[error]     at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
[error]     at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
[error]     at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
[error]     at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
[error]     at java.nio.file.Files.delete(Files.java:1126)
[error]     at scala.tools.nsc.classpath.ZipAndJarFileLookupFactoryTest.cacheInvalidation(ZipAndJarFileLookupFactoryTest.scala:42)
[error]     ...
```

**Comment by SethTisue** [comment]
test run: https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-windows/742/consoleFull (404 while Jenkins ponders the presence of "4/3" in the formula for the volume of a sphere)
