### ISSUE TITLE
2.13.x-integrate-windows has been failing since Sep 13

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#429]
first red run: https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-windows/318/

**Comment by adriaanm** [comment]
```
[error] Test scala.tools.nsc.classpath.ZipAndJarFileLookupFactoryTest.cacheInvalidation failed: java.nio.file.FileSystemException: y:\jenkins\tmp\test-8354326820267605177.jar: The process cannot access the file because it is being used by another process.

[error] , took 0.041 sec
[error]     at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
[error]     at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
[error]     at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
[error]     at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
[error]     at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
[error]     at java.nio.file.Files.delete(Files.java:1126)
[error]     at scala.tools.nsc.classpath.ZipAndJarFileLookupFactoryTest.cacheInvalidation(ZipAndJarFileLookupFactoryTest.scala:42)
[error]     ...
```

i'll start by nuking `y:\jenkins\tmp`

**Comment by SethTisue** [comment]
@adriaanm oh I think @retronym already fixed this on 2.12.x and it just needs to be merged forward

**Comment by adriaanm** [comment]
Thanks, for ref: https://github.com/scala/scala/commit/3d7e5c3888e0c0ce46315ea6918fd03b22f1fcb4

**Comment by adriaanm** [comment]
Merge PR: https://github.com/scala/scala/pull/6086

**Comment by SethTisue** [comment]
`Jenkins build is back to normal : scala-2.13.x-integrate-windows [325] scala/scala#2.13.x`
