### ISSUE TITLE
investigate new 2.13 community build regressions

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#466]
https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/919/consoleFull (Scala version `2.13.0-pre-79e5101`) and other recent runs have:

```
[info] >>> The dbuild result is------------: FAILED (failed: utest, scala-continuations, akka-actor)
```

careful, fixing these might uncover additional failures

**Comment by SethTisue** [comment]
scala-continuations: regression reported at https://github.com/scala/scala-continuations/issues/37. pulled it from the 2.13 build in scala/community-builds@86972c2b336c7298b03de425589cd4362ecccdbf

**Comment by SethTisue** [comment]
the exact nature of the utest failures isn't obvious. some of them are `utest.NoSuchTestException`s, others are assertion failures involving implicit lookup.

there have indeed been changes to implicit lookup lately in 2.13, so since we're eager to get M3 out the door, I think it's a reasonably safe bet this isn't a release blocker. I've reported it upstream at https://github.com/lihaoyi/utest/issues/149 and disabled the test suite in the community build (scala/community-builds@e1ae04a338d27746bb85e4fb6b7b0f912fd60650)

**Comment by SethTisue** [comment]
the Akka thing looks like a regression in the interaction of `@tailrec` and singleton types. I've made a separate ticket on it at https://github.com/scala/scala-dev/issues/467 for @milessabin to look at. I don't think this is a blocker for release, so I'll deal with it in the community build by temporarily forking Akka and removing the `@tailrec`s in question (scala/community-builds@6ba025d287b16ce3060e98e6f98fe9512dd7d5c3)

**Comment by SethTisue** [comment]
test run: ~~https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/921/consoleFull~~ https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/922/consoleFull

**Comment by SethTisue** [comment]
akka-actor builds now (with the `@tailrec` removal), tests pass.

dbuild is giving a weird error on utest. looking into it

```
[utest] Retrieved from project scalacheck (commit: 9b71bb3dfe186c03292faa59976487af2ee23caa): 4 artifacts
[utest:error] scala.MatchError: f38684f7+20180129-1910 (of class java.lang.String)
[utest:error] 	at com.typesafe.dbuild.project.build.LocalBuildRunner$.prepareDepsArtifacts(LocalBuildRunner.scala:110)
[utest:error] 	at com.typesafe.dbuild.project.build.LocalBuildRunner$$anonfun$runLocalBuild$1.apply(LocalBuildRunner.scala:57)
[utest:error] 	at com.typesafe.dbuild.project.build.LocalBuildRunner$$anonfun$runLocalBuild$1.apply(LocalBuildRunner.scala:47)
[utest:error] 	at com.typesafe.dbuild.project.build.BuildDirs$.useProjectUniqueBuildDir(BuildDirs.scala:41)
[utest:error] 	at com.typesafe.dbuild.project.build.LocalBuildRunner.runLocalBuild(LocalBuildRunner.scala:47)
[utest:error] 	at com.typesafe.dbuild.project.build.LocalBuildRunner.checkCacheThenBuild(LocalBuildRunner.scala:36)
```

EDIT: I bet this has to do with sbt-dynver. in our fork,

```
> show utestJVM/version
[info] 0.6.3+11-f38684f7
```

I'll see if ~~pushing a `0.6.3.1` tag~~ pushing an empty commit and a `v0.6.3.2` tag fixes it.

https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/924/consoleFull

**Comment by SethTisue** [comment]
hmm, my utest fix passes locally, fails on Jenkins. I `git clean -fdx`ed the workspace, let's try again: https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-community-build/926/consoleFull

if this doesn't fix it, maybe I'll need to blow away `~/.dbuild`

**Comment by SethTisue** [comment]
the entire build is green locally, so that means we're good to go for M3. but I'll leave this open til I get it green on Jenkins too

**Comment by SethTisue** [comment]
🍏🥝☘️✅💚

**Comment by SethTisue** [comment]
scala/community-builds@3690f90ee06c324b61ed000fcae5fb58ff62d0fc freezes all project SHAs at last used revisions until M3 is out the door
