### ISSUE TITLE
bootstrap job fails to find sbt-pgp on jenkins

### ISSUE THREAD

**Issue by lrytz** [scala/scala-dev#481]
For example https://scala-ci.typesafe.com/view/scala-bench/job/bootstrap-benchmark/642/console

```
sbt.ResolveException: unresolved dependency: com.typesafe.sbt#sbt-pgp;0.8.1: not found
```

**Comment by retronym** [comment]
```bash
# scripts/common provides sbtRepositoryConfig
sbtArgs="-ivy $IVY2_DIR -Dsbt.override.build.repos=true -Dsbt.repository.config=$sbtRepositoryConfig"

source scripts/bootstrap_fun

determineScalaVersion 
```

I think the problem is that `determineScalaVersion` above calls SBT with `-Dsbt.repository.config=$sbtRepositoryConfig` before `generateRepositoriesConfig` below actually generates the config file.

```bash
deriveModuleVersions

generateRepositoriesConfig $integrationRepoUrl
```

**Comment by retronym** [comment]
I tried to test a fix in the last commit of https://github.com/scala/scala/pull/6214, but I think I've managed to get the benchq stuck, maybe by retrying a failed build of the prior commit?

![image](https://user-images.githubusercontent.com/65551/37750907-0fb08eb4-2ddb-11e8-808b-882ad5400810.png)
![image](https://user-images.githubusercontent.com/65551/37750935-3c474030-2ddb-11e8-8c12-8d353af9f8c2.png)

**Comment by retronym** [comment]
Kicked it off manually in https://scala-ci.typesafe.com/view/scala-bench/job/bootstrap-benchmark/644/

**Comment by retronym** [comment]
Either a problem with my attempted fix, or the next problem to solve:

```
[warn] bnd: Unused Private-Package instructions, no such package(s) on the class path: [org.scala-lang.modules.scala-xml.*]
java.io.IOException: Access to URL https://scala-ci.typesafe.com/artifactory/scala-integration/org/scala-lang/modules/scala-xml_2.13.0-pre-32ff048/1.1.0/scala-xml_2.13.0-pre-32ff048-1.1.0.pom was refused by the server: Forbidden
	at org.apache.ivy.util.url.AbstractURLHandler.validatePutStatusCode(AbstractURLHandler.java:79)
	at org.apache.ivy.util.url.BasicURLHandler.upload(BasicURLHandler.java:264)
	at org.apache.ivy.util.FileUtil.copy(FileUtil.java:150)
	at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:84)
	at sbt.ConvertResolver$LocalIfFileRepo.put(ConvertResolver.scala:243)
```

**Comment by retronym** [comment]
> I think I've managed to get the benchq stuck, maybe by retrying a failed build of the prior commit?

I deleted two "WaitingForScalaBuild" entries `compilerBenchmarkTaskService` in the admin console.

Now, there are these two wanting to start:

```
scala> compilerBenchmarkTaskService.byIndex(Set(StartScalaBuild)).mkString("\n")
res4: String =
CompilerBenchmarkTask(100,StartScalaBuild,scala/scala#e93a90108677c23b319154c7a32a3031620c06ad,List(hot -p source=better-files -wi 10 -w 10 -i 10 -r 10 -f 3, hot -p source=scalap -wi 10 -w 10 -i 10 -r 10 -f 3, hot -p source=scala -wi 3 -w 240 -i 2 -r 240 -f 4))
CompilerBenchmarkTask(100,StartScalaBuild,scala/scala#32ff0485ea87efd5adbf587da9aa69eb3f4ae8c1,List(hot -p source=better-files -wi 10 -w 10 -i 10 -r 10 -f 3, hot -p source=scalap -wi 10 -w 10 -i 10 -r 10 -f 3, hot -p source=vector -wi 10 -w 10 -i 10 -r 10 -f 3))


scala> compilerBenchmarkTaskService.byIndex(Set(WaitForScalaBuild))
res6: List[benchq.model.CompilerBenchmarkTask] = List()
```

But the didn't seem to be triggered by the `PingQueue` event. I'm wondering if we're losing the `PingQueue` rhythym after the recent [travis change](https://github.com/scala/compiler-benchq/commit/34ce5b9d2ed958ddf77fc7e6d7a51cf984965c9b#r28210297). But the application logs don't show that line of code being logged since I just restarted the service..


```
benchq@ip-172-31-0-100:~$ grep "No unique task for travis build" /home/benchq/benchq-data/logs/application.log
2018-03-10 06:55:53,537 [INFO] from application in application-akka.actor.default-dispatcher-31 - No unique task for travis build (30f2646b114e0d46b5b3e37dc322ee67cf37ea71): List()
2018-03-10 06:56:09,143 [INFO] from application in application-akka.actor.default-dispatcher-30 - No unique task for travis build (30f2646b114e0d46b5b3e37dc322ee67cf37ea71): List()
2018-03-11 06:41:48,518 [INFO] from application in application-akka.actor.default-dispatcher-97 - No unique task for travis build (30f2646b114e0d46b5b3e37dc322ee67cf37ea71): List()
2018-03-14 10:24:03,007 [INFO] from application in application-akka.actor.default-dispatcher-936 - No unique task for travis build (1d51494599cf64dc4024394c1cf2bce31a922e85): List()
2018-03-14 11:27:39,599 [INFO] from application in application-akka.actor.default-dispatcher-960 - No unique task for travis build (1d51494599cf64dc4024394c1cf2bce31a922e85): List()
2018-03-14 13:49:22,288 [INFO] from application in application-akka.actor.default-dispatcher-984 - No unique task for travis build (d203b870a9fe8464ed8325586e92f1e3540a2dea): List()
2018-03-15 17:22:26,130 [INFO] from application in application-akka.actor.default-dispatcher-1173 - No unique task for travis build (1bb014a5691c56c4a97f2968078f05a37243012d): List()
2018-03-19 13:36:25,479 [INFO] from application in application-akka.actor.default-dispatcher-1567 - No unique task for travis build (97433c9849e146d060d329e81e786478f26969b9): List()
2018-03-19 22:01:11,835 [INFO] from application in application-akka.actor.default-dispatcher-1616 - No unique task for travis build (6b61a5d8e09df0456ad6e83f256f12e65bdcd59a): List()
2018-03-20 06:29:38,633 [INFO] from application in application-akka.actor.default-dispatcher-1663 - No unique task for travis build (30a1428925497a7358fd386db84fd982c3108707): List()
benchq@ip-172-31-0-100:~$ date
Thu Mar 22 06:32:46 UTC 2018
```

**Comment by retronym** [comment]
> Either a problem with my attempted fix, or the next problem to solve:

I've hacked on an export of the missing environment variable into the boostrap script on my PR, which seems to get the build working again:

```
  if [[ "$PRIVATE_REPO_PASS" = "" ]]; then
    tracestate="$(shopt -po xtrace)"
    set +x
    PRIVATE_REPO_PASS=$(cat "$HOME/.credentials-private-repo" | grep password= | sed -e 's/password=//')
    eval "$tracestate"
  fi
  echo $PRIVATE_REPO_PASS
```

I guess we should just stick configure PRIVATE_REPO_PASS in the environment vars of the `jenkins` user (how, exactly?). On the regular workers, where we plan to run the boostrap-bootstrap job , the credentials are available under `.credentials`.
