### ISSUE TITLE
2.13 merge builds fail after partest in-sourcing

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#510]
seen at e.g. https://travis-ci.org/scala/scala/jobs/377745237

```
java.io.IOException: PUT operation to URL https://scala-ci.typesafe.com/artifactory/scala-integration/org/scala-lang/modules/scala-partest_2.13.0-pre-7cb938b/scala-partest_2.13.0-pre-7cb938b-.pom failed with status code 409: Conflict
	at org.apache.ivy.util.url.AbstractURLHandler.validatePutStatusCode(AbstractURLHandler.java:82)
	at org.apache.ivy.util.url.BasicURLHandler.upload(BasicURLHandler.java:264)
	at org.apache.ivy.util.FileUtil.copy(FileUtil.java:150)
	at org.apache.ivy.plugins.repository.url.URLRepository.put(URLRepository.java:84)
	at sbt.ConvertResolver$LocalIfFileRepo.put(ConvertResolver.scala:243)
	at org.apache.ivy.plugins.repository.AbstractRepository.put(AbstractRepository.java:130)
```

@lrytz I think you might be best placed to fix this...? is it trying to publish partest twice?

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/6637
