### ISSUE TITLE
sbt intellij fails

### ISSUE THREAD

**Issue by jozic** [scala/scala-dev#555]
not 100% sure if this belongs here, but it's more related to dev then the lang and/or library
please move to scala/bug if fits there better

```bash
➜  scala git:(2.13.x) sbt intellij
[info] Loading global plugins from /home/jozic/.sbt/0.13/plugins
[info] Loading project definition from /home/jozic/projects/github/scala/project/project
[info] Loading project definition from /home/jozic/projects/github/scala/project
[info] Resolving key references (11731 settings) ...
[info] *** Welcome to the sbt build definition for Scala! ***
[info] Check README.md for more information.
Update library classpaths in the current src/intellij/scala.ipr (y/N)? y
[info] Updating library classpaths in src/intellij/scala.ipr.
java.lang.RuntimeException: Replacing library classpath for bench-deps failed, no existing library found.
	at scala.sys.package$.error(package.scala:27)
	at $18070cfe99fd832939d2$$anonfun$$sbtdef$1.$18070cfe99fd832939d2$$anonfun$$replaceLibrary$1(/home/jozic/projects/github/scala/build.sbt:1180)
	at $18070cfe99fd832939d2$$anonfun$$sbtdef$1$$anonfun$4.apply(/home/jozic/projects/github/scala/build.sbt:1207)
	at $18070cfe99fd832939d2$$anonfun$$sbtdef$1$$anonfun$4.apply(/home/jozic/projects/github/scala/build.sbt:1204)
	at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
	at scala.collection.immutable.List.foldLeft(List.scala:84)
	at $18070cfe99fd832939d2$$anonfun$$sbtdef$1.apply(/home/jozic/projects/github/scala/build.sbt:1204)
	at $18070cfe99fd832939d2$$anonfun$$sbtdef$1.apply(/home/jozic/projects/github/scala/build.sbt:1102)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[error] (root/*:intellij) Replacing library classpath for bench-deps failed, no existing library found.
[error] Total time: 52 s, completed Sep 7, 2018 8:34:52 AM
➜  scala git:(2.13.x) 
```

**Comment by lrytz** [comment]
In this case the existing files don't have the expected shape... Run `intellijFromSample` and then `intellij`. Please re-open if that doesn't work.

**Comment by jozic** [comment]
thanks @lrytz, that worked, may be worth mentioning in the doc. 
I see there's a note about `intellijFromSample`, but it wasn't clear to me that i need to run that to fix the failure
