### ISSUE TITLE
t10823 sys.process test failing on Windows

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#589]
https://scala-ci.typesafe.com/view/scala-2.13.x/job/scala-2.13.x-integrate-windows/797/

```
Exception in thread "ThreadProcess-spawn-Thread-29" java.io.FileNotFoundException: total\junk (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at scala.sys.process.ProcessBuilderImpl$FileInput$$anonfun$$lessinit$greater$2.apply(ProcessBuilderImpl.scala:37)
	at scala.sys.process.ProcessBuilderImpl$FileInput$$anonfun$$lessinit$greater$2.apply(ProcessBuilderImpl.scala:37)
	at scala.sys.process.ProcessBuilderImpl$IStreamBuilder$$anonfun$$lessinit$greater$5.apply(ProcessBuilderImpl.scala:50)
	at scala.sys.process.ProcessBuilderImpl$IStreamBuilder$$anonfun$$lessinit$greater$5.apply(ProcessBuilderImpl.scala:50)
	at scala.sys.process.ProcessBuilderImpl$ThreadBuilder.go$1(ProcessBuilderImpl.scala:64)
	at scala.sys.process.ProcessBuilderImpl$ThreadBuilder.$anonfun$run$1(ProcessBuilderImpl.scala:68)
	at scala.sys.process.ProcessImpl$Spawn$$anon$1.run(ProcessImpl.scala:25)
[error] Test scala.sys.process.ProcessTest.t10823_short_circuit failed: java.nio.file.FileSystemException: y:\jenkins\tmp\out2048718722953092598tmp: The process cannot access the file because it is being used by another process.
[error] , took 0.013 sec
[error]     at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
[error]     at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
[error]     at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
[error]     at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
[error]     at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
[error]     at java.nio.file.Files.delete(Files.java:1126)
[error]     at scala.sys.process.ProcessTest.t10823_short_circuit(ProcessTest.scala:112)
[error]     ...
```

@som-snytt I'm not sure why the runs I did on your big PR didn't catch this in advance, maybe some other recently merged sys.process PR is responsible?

**Comment by som-snytt** [comment]
I'll put it behind `!isWin`. I've never understood that windows thing where I can't delete a file because it thinks it's in use.

It's complaining about the output file in `src.cat #&& mock`, there is no other process.

"When the Lord closes a bug, He opens another in a place you least expect it."
