### ISSUE TITLE
Intermittent error in CI in recently added PipelineMainTest

### ISSUE THREAD

**Issue by retronym** [scala/scala-dev#637]
The assertion error doesn't tell us much because originally I figured we'd always be seeing the error locally and could just run `jardiff a b` to get a detailed diff.

```
[0m[[0minfo[0m] [0mTest scala.reflect.internal.util.[33mFileUtilsTest[0m.[36mwriteIsSame[0m started[0m
[0m[[0minfo[0m] [0m[34mTest run finished: [0m[34m0 failed[0m[34m, [0m[34m0 ignored[0m[34m, 2 total, 2.775s[0m[0m
[0m[[0minfo[0m] [0m[34mTest run started[0m[0m
[0m[[0minfo[0m] [0mTest scala.tools.nsc.[33mPipelineMainTest[0m.[36mpipelineMainBuildsSeparate[0m started[0m
[0m[[31merror[0m] [0mTest scala.tools.nsc.[33mPipelineMainTest[0m.[31mpipelineMainBuildsSeparate[0m failed: java.lang.[31mAssertionError[0m: assertion failed: Difference detected between recompiling Pipeline Run:[0m
[0m[[31merror[0m] [0mjardiff -r /tmp/pipelineBase5880286432145723497/Traditional/classes /tmp/pipelineBase5880286432145723497/Pipeline/classes[0m
[0m[[31merror[0m] [0m, took 6.071 sec[0m
[0m[[31merror[0m] [0m    at scala.tools.nsc.FileUtils$.assertDirectorySame(FileUtils.scala:11)[0m
[0m[[31merror[0m] [0m    at scala.tools.nsc.PipelineMainTest.$anonfun$check$3([35mPipelineMainTest.scala[0m:[33m76[0m)[0m
[0m[[31merror[0m] [0m    at scala.tools.nsc.PipelineMainTest.check([35mPipelineMainTest.scala[0m:[33m71[0m)[0m
[0m[[31merror[0m] [0m    at scala.tools.nsc.PipelineMainTest.pipelineMainBuildsSeparate([35mPipelineMainTest.scala[0m:[33m36[0m)[0m
[0m[[31merror[0m] [0m    ...[0m
[0m[[0minfo[0m] [0mTest scala.tools.nsc.[33mPipelineMainTest[0m.[36mpipelineMainBuildsJavaAccessor[0m started[0m
[0m[[0minfo[0m] [0mTest scala.tools.nsc.[33mPipelineMainTest[0m.[36mpipelineMainBuildsCombined[0m started[0m
```

**Comment by retronym** [comment]
I believe the problem is that `PipelineMain.main` is exiting without properly waiting for threads to finish, or maybe for files to be closed.

```
[0m[[31merror[0m] [0mjardiff -r /tmp/pipelineBase728861260593797496/Traditional/classes /tmp/pipelineBase728861260593797496/Pipeline/classes[0m
[0m[[31merror[0m] [0mMissing(../../../../../..,/tmp/pipelineBase728861260593797496/Traditional/classes/b3/p2/target/b3/p2/JavaClient.class), took 7.862 sec[0m
[0m[[31merror[0m] [0m    at scala.tools.nsc.FileUtils$.assertDirectorySame(FileUtils.scala:27)[0m
[0m[[31merror[0m] [0m    at scala.tools.nsc.PipelineMainTest.$anonfun$check$3([35mPipelineMainTest.scala[0m:[33m76[0m)[0m
[0m[[31merror[0m] [0m    at scala.tools.nsc.PipelineMainTest.check([35mPipelineMainTest.scala[0m:[33m71[0m)[0m
[0m[[31merror[0m] [0m    at scala.tools.nsc.PipelineMainTest.pipelineMainBuildsSeparate([35mPipelineMainTest.scala[0m:[33m36[0m)[0m
```

**Comment by retronym** [comment]
I can reproduce this on Jenkins now with https://scala-ci.typesafe.com/job/scala-2.12.x-validate-main/1933/console / https://github.com/retronym/scala/tree/ticket/sd637-repro

**Comment by retronym** [comment]
```
/var/folders/tz/p8vd07wn7wxck3b9v54grlzw0000gp/T/pipelineBase5608394793732995483/projects/b4/p2/src/b4/p2/JavaClient.java:4: error: cannot find symbol
  symbol:   class JavaDefined
  location: package b3.p1
  b3.p1.JavaDefined<String> test() { return null; }
       ^
/var/folders/tz/p8vd07wn7wxck3b9v54grlzw0000gp/T/pipelineBase5608394793732995483/projects/b3/p2/src/b3/p2/JavaClient.java:4: error: cannot find symbol
  symbol:   class JavaDefined
  location: package b3.p1
  b3.p1.JavaDefined<String> test() { return null; }
       ^
b4.p2.args: javac: error 26 ms
b3.p2.args: javac: error 35 ms
b5.p1.args: javac: done 17 ms
m1.p1.args: scalac: done 117 ms
b1.p1.args: scalac (1/1): start
m1.internalMacroClient.args: scalac (1/1): start
-classpath
/var/folders/tz/p8vd07wn7wxck3b9v54grlzw0000gp/T/scala.picklecache5230600457211426725/var/folders/tz/p8vd07wn7wxck3b9v54grlzw0000gp/T/pipelineBase5608394793732995483/projects/m1/p1/target.jar
-Ymacro-classpath
/var/folders/tz/p8vd07wn7wxck3b9v54grlzw0000gp/T/pipelineBase5608394793732995483/projects/m1/p1/target
-usejavacp
-d
/var/folders/tz/p8vd07wn7wxck3b9v54grlzw0000gp/T/pipelineBase5608394793732995483/projects/b1/p1/target
-Ycache-plugin-class-loader:always
-Ycache-macro-class-loader:always
/var/folders/tz/p8vd07wn7wxck3b9v54grlzw0000gp/T/pipelineBase5608394793732995483/projects/b1/p1/src/b1/p1/ExternalClient.scala
-classpath
/var/folders/tz/p8vd07wn7wxck3b9v54grlzw0000gp/T/scala.picklecache5230600457211426725/var/folders/tz/p8vd07wn7wxck3b9v54grlzw0000gp/T/pipelineBase5608394793732995483/projects/m1/p1/target.jar
-Ymacro-classpath
/var/folders/tz/p8vd07wn7wxck3b9v54grlzw0000gp/T/pipelineBase5608394793732995483/projects/m1/p1/target
-usejavacp
-Ycache-plugin-class-loader:always
-d
/var/folders/tz/p8vd07wn7wxck3b9v54grlzw0000gp/T/pipelineBase5608394793732995483/projects/m1/internalMacroClient/target
-Ycache-macro-class-loader:always
/var/folders/tz/p8vd07wn7wxck3b9v54grlzw0000gp/T/pipelineBase5608394793732995483/projects/m1/internalMacroClient/src/m2/p2/InternalClient.scala
b1.p1.args: scalac (1/1): done 126 ms
m1.internalMacroClient.args: scalac (1/1): done 126 ms
PROGRESS: 24 / 24
 Wall Clock: 500 ms
Wrote project dependency graph to: /var/folders/tz/p8vd07wn7wxck3b9v54grlzw0000gp/T/pipelineBase5608394793732995483/Pipeline/projects.dot
Chrome trace written to /var/folders/tz/p8vd07wn7wxck3b9v54grlzw0000gp/T/pipelineBase5608394793732995483/Pipeline/build-1.trace
[error] Test scala.tools.nsc.PipelineMainTest.pipelineMainBuildsCombined failed: java.lang.AssertionError: assertion failed: Difference detected between recompiling Pipeline Run:
```

**Comment by dwijnand** [comment]
Fixed in https://github.com/scala/scala/pull/8170
