### ISSUE TITLE
Test failures on Windows (run/t5717.scala, ​run/t6502.scala)

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#638]
starting a few days ago these started consistently failing at https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-windows/

```
!! 1267 - run/t5717.scala                           [output differs]
% diff Y:\jenkins\workspace\scala-2.12.x-integrate-windows\test\files\run\t5717-run.log Y:\jenkins\workspace\scala-2.12.x-integrate-windows\test\files\run\t5717.check--- t5717-run.log
+++ empty
@@ -1,44 +1,0 @@
-java.lang.AssertionError: assertion failed: error writing t5717-run.obj/a/B.class: Can't create directory t5717-run.obj/a; there is an existing (non-directory) file in its path
-	at Test$.show(t5717.scala:25)
-	at scala.tools.partest.DirectTest.delayedEndpoint$scala$tools$partest$DirectTest$1(DirectTest.scala:92)
-	at scala.tools.partest.DirectTest$delayedInit$body.apply(DirectTest.scala:18)
```

```
!! 1422 - run/t6502.scala                           [output differs]
% diff Y:\jenkins\workspace\scala-2.12.x-integrate-windows\test\files\run\t6502-run.log Y:\jenkins\workspace\scala-2.12.x-integrate-windows\test\files\run\t6502.check--- t6502-run.log
+++ empty
@@ -1,45 +1,0 @@
-java.lang.AssertionError: assertion failed: scala> <console>:12: error: not found: value test
-	at Test$.test1(t6502.scala:67)
-	at Test$.show(t6502.scala:150)
-	at scala.tools.partest.DirectTest.delayedEndpoint$scala$tools$partest$DirectTest$1(DirectTest.scala:92)
```

**Comment by SethTisue** [comment]
@retronym the cause appears to be https://github.com/scala/scala/pull/8175

**Comment by retronym** [comment]
Thanks, Seth. I'm on it.

**Comment by dwijnand** [comment]
Fixed in https://github.com/scala/scala/pull/8233

**Comment by SethTisue** [comment]
after latest 2.12.x->2.13.x merge, it's green on 2.13 too: https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-windows/1047/
