### ISSUE TITLE
2.12 community build: regression in scala-js

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#64]
recently scala-js started failing in the 2.12 community build, details below.

@lrytz this looks like it might be a consequence of https://github.com/scala/scala/pull/4838 . can you take a look and see whether the next move is yours or @sjrd's?

from: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/220/consoleFull:

```
[scala-js] [error] error: java.lang.NullPointerException
[scala-js] [error]  at scala.tools.nsc.backend.jvm.CoreBTypesProxy.primitiveTypeMap(CoreBTypes.scala:222)
[scala-js] [error]  at scala.tools.nsc.backend.jvm.BTypesFromSymbols.primitiveOrClassToBType$1(BTypesFromSymbols.scala:155)
[scala-js] [error]  at scala.tools.nsc.backend.jvm.BTypesFromSymbols.typeToBType(BTypesFromSymbols.scala:170)
[scala-js] [error]  at scala.tools.nsc.backend.ScalaPrimitives.getPrimitive(ScalaPrimitives.scala:585)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genPrimitiveOp(GenJSCode.scala:2366)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genApply(GenJSCode.scala:1615)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:1217)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genExpr(GenJSCode.scala:1145)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.org$scalajs$core$compiler$GenJSCode$JSCodePhase$$$anonfun$178(GenJSCode.scala:3719)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.org$scalajs$core$compiler$GenJSCode$JSCodePhase$$$anonfun$178$adapted(GenJSCode.scala:3713)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$Lambda$2752/296586505.apply(Unknown Source)
[scala-js] [error]  at scala.collection.TraversableLike$WithFilter.scala$collection$TraversableLike$WithFilter$$$anonfun$40(TraversableLike.scala:778)
[scala-js] [error]  at scala.collection.TraversableLike$WithFilter$$Lambda$342/50503805.apply(Unknown Source)
[scala-js] [error]  at scala.collection.immutable.List.foreach(List.scala:378)
[scala-js] [error]  at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:777)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genPrimitiveJSArgs(GenJSCode.scala:3713)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genPrimitiveJSNew(GenJSCode.scala:3605)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genApplyNew(GenJSCode.scala:1739)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genApply(GenJSCode.scala:1609)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:1217)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genExpr(GenJSCode.scala:1145)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.org$scalajs$core$compiler$GenJSCode$JSCodePhase$$$anonfun$169(GenJSCode.scala:3659)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$Lambda$2726/2131518213.apply(Unknown Source)
[scala-js] [error]  at scala.collection.TraversableLike$WithFilter.scala$collection$TraversableLike$WithFilter$$$anonfun$38(TraversableLike.scala:728)
[scala-js] [error]  at scala.collection.TraversableLike$WithFilter$$Lambda$525/1292472219.apply(Unknown Source)
[scala-js] [error]  at scala.collection.immutable.List.foreach(List.scala:378)
[scala-js] [error]  at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:727)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genActualArgs(GenJSCode.scala:3650)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genNormalApply(GenJSCode.scala:1882)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genApply(GenJSCode.scala:1625)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:1217)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genExpr(GenJSCode.scala:1145)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genApplyTypeApply(GenJSCode.scala:1650)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genApply(GenJSCode.scala:1600)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genStatOrExpr(GenJSCode.scala:1217)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genExpr(GenJSCode.scala:1145)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genBody$1(GenJSCode.scala:1101)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genMethodDef(GenJSCode.scala:1105)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.org$scalajs$core$compiler$GenJSCode$JSCodePhase$$$anonfun$40(GenJSCode.scala:793)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$Lambda$2712/1350082590.apply(Unknown Source)
[scala-js] [error]  at org.scalajs.core.compiler.util.ScopedVar$.withScopedVars(ScopedVar.scala:35)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.org$scalajs$core$compiler$GenJSCode$JSCodePhase$$$anonfun$36(GenJSCode.scala:754)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$Lambda$2706/1277574556.apply(Unknown Source)
[scala-js] [error]  at org.scalajs.core.compiler.util.ScopedVar$.withScopedVars(ScopedVar.scala:35)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genMethodWithCurrentLocalNameScope(GenJSCode.scala:720)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.org$scalajs$core$compiler$GenJSCode$JSCodePhase$$$anonfun$35(GenJSCode.scala:685)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$Lambda$2705/1357357624.apply(Unknown Source)
[scala-js] [error]  at org.scalajs.core.compiler.util.ScopedVar$.withScopedVars(ScopedVar.scala:35)
[scala-js] [error]  at org.scalajs.core.compiler.JSEncoding$class.withNewLocalNameScope(JSEncoding.scala:54)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode.withNewLocalNameScope(GenJSCode.scala:30)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genMethod(GenJSCode.scala:685)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.gen$1(GenJSCode.scala:337)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.org$scalajs$core$compiler$GenJSCode$JSCodePhase$$$anonfun$15(GenJSCode.scala:322)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.org$scalajs$core$compiler$GenJSCode$JSCodePhase$$$anonfun$15$adapted(GenJSCode.scala:322)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$Lambda$2704/1404945237.apply(Unknown Source)
[scala-js] [error]  at scala.collection.immutable.List.foreach(List.scala:378)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.gen$1(GenJSCode.scala:322)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.genClass(GenJSCode.scala:349)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.org$scalajs$core$compiler$GenJSCode$JSCodePhase$$$anonfun$8(GenJSCode.scala:257)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$Lambda$2683/2083966486.apply(Unknown Source)
[scala-js] [error]  at org.scalajs.core.compiler.util.ScopedVar$.withScopedVars(ScopedVar.scala:35)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.org$scalajs$core$compiler$GenJSCode$JSCodePhase$$$anonfun$7(GenJSCode.scala:244)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase$$Lambda$2682/543617235.apply(Unknown Source)
[scala-js] [error]  at scala.collection.immutable.List.foreach(List.scala:378)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.apply(GenJSCode.scala:227)
[scala-js] [error]  at scala.tools.nsc.Global$GlobalPhase.scala$tools$nsc$Global$GlobalPhase$$$anonfun$11(Global.scala:424)
[scala-js] [error]  at scala.tools.nsc.Global$GlobalPhase$$Lambda$411/2002174925.apply$mcV$sp(Unknown Source)
[scala-js] [error]  at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:415)
[scala-js] [error]  at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:424)
[scala-js] [error]  at scala.tools.nsc.Global$GlobalPhase.scala$tools$nsc$Global$GlobalPhase$$$anonfun$10(Global.scala:382)
[scala-js] [error]  at scala.tools.nsc.Global$GlobalPhase.scala$tools$nsc$Global$GlobalPhase$$$anonfun$10$adapted(Global.scala:382)
[scala-js] [error]  at scala.tools.nsc.Global$GlobalPhase$$Lambda$410/1966670937.apply(Unknown Source)
[scala-js] [error]  at scala.collection.Iterator$class.foreach(Iterator.scala:893)
[scala-js] [error]  at scala.collection.AbstractIterator.foreach(Iterator.scala:1370)
[scala-js] [error]  at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:382)
[scala-js] [error]  at org.scalajs.core.compiler.GenJSCode$JSCodePhase.run(GenJSCode.scala:165)
[scala-js] [error]  at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1415)
[scala-js] [error]  at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1400)
[scala-js] [error]  at scala.tools.nsc.Global$Run.compileSources(Global.scala:1395)
[scala-js] [error]  at scala.tools.nsc.Global$Run.compile(Global.scala:1489)
[scala-js] [error]  at scala.tools.nsc.Driver.doCompile(Driver.scala:35)
[scala-js] [error]  at scala.tools.nsc.MainClass.doCompile(Main.scala:24)
[scala-js] [error]  at scala.tools.nsc.Driver.process(Driver.scala:55)
[scala-js] [error]  at scala.tools.nsc.Driver.main(Driver.scala:68)
[scala-js] [error]  at scala.tools.nsc.Main.main(Main.scala)
```

**Comment by lrytz** [comment]
Indeed, thanks Seth for noticing.

@sjrd it's probably just a matter of adding `bTypes.initializeCoreBTypes()` in [`GenJSCode`](https://github.com/scala-js/scala-js/blob/master/compiler/src/main/scala/org/scalajs/core/compiler/GenJSCode.scala#L163), here's what we do in [`GenBCode`](https://github.com/scala/scala/blob/5cb3d4ec14488ce2fc5a1cc8ebdd12845859c57d/src/compiler/scala/tools/nsc/backend/jvm/GenBCode.scala#L330-L331)

**Comment by sjrd** [comment]
I see. We'll probably need more implicit magic to make that compile in 2.10, but that should be doable.

**Comment by sjrd** [comment]
Using `++2.12.0-SNAPSHOT` doesn't seem to cause any failure on my side. I guess this is not the right way to get the very latest Scala 2.12. How can I do that? Do I need to compile scala locally?

**Comment by sjrd** [comment]
Well, I made a "blind" fix in https://github.com/scala-js/scala-js/pull/2030 anyway. @SethTisue Would it be possible to run the community build with this PR included somehow, to verify that this actually fix the problem?

**Comment by lrytz** [comment]
we don't currently publish snapshots, but this should come back at some point (https://github.com/scala/scala-jenkins-infra/issues/133). you can use the builds from our jenkins:

```
resolvers += "pr" at "https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/"
scalaVersion :=  "2.12.0-5cb3d4e-SNAPSHOT"
```

**Comment by sjrd** [comment]
Thanks. I was able to reproduce the crash with those settings; and could test that the fix fixes it.

**Comment by sjrd** [comment]
The fix landed in Scala.js master.
