### ISSUE TITLE
JLine 3: replay session when entry seems to have slain the compiler

### ISSUE THREAD

**Issue by Jasper-M** [scala/scala-dev#705]
Doesn't work anymore.
```
scala> case class Foo(x: Int) extends AnyVal
java.lang.NumberFormatException: For input string: "1$extension"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at scala.reflect.internal.StdNames$TermNames.splitDefaultGetterName(StdNames.scala:520)
	at scala.tools.nsc.typechecker.TypeDiagnostics$UnusedPrivates.rescindPrivateConstructorDefault$1(TypeDiagnostics.scala:595)
	at scala.tools.nsc.typechecker.TypeDiagnostics$UnusedPrivates.isSyntheticWarnable(TypeDiagnostics.scala:598)
	at scala.tools.nsc.typechecker.TypeDiagnostics$UnusedPrivates.isUnusedTerm(TypeDiagnostics.scala:603)
	at scala.tools.nsc.typechecker.TypeDiagnostics$UnusedPrivates.$anonfun$unusedTerms$1(TypeDiagnostics.scala:628)
	at scala.tools.nsc.typechecker.TypeDiagnostics$UnusedPrivates.unusedTerms(TypeDiagnostics.scala:628)
	at scala.tools.nsc.interpreter.ReplGlobal$wrapperCleanup$WrapperCleanupTransformer.transform(ReplGlobal.scala:76)
	at scala.tools.nsc.interpreter.ReplGlobal$wrapperCleanup$WrapperCleanupTransformer.transform(ReplGlobal.scala:63)
	at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2587)
	at scala.reflect.internal.Trees$ModuleDef.$anonfun$transform$3(Trees.scala:370)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2625)
	at scala.reflect.internal.Trees$ModuleDef.transform(Trees.scala:369)
	at scala.reflect.internal.Trees$InternalTransformer.transform(Trees.scala:1461)
	at scala.tools.nsc.interpreter.ReplGlobal$wrapperCleanup$WrapperCleanupTransformer.transform(ReplGlobal.scala:72)
	at scala.tools.nsc.interpreter.ReplGlobal$wrapperCleanup$WrapperCleanupTransformer.transform(ReplGlobal.scala:63)
	at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2614)
	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2612)
	at scala.reflect.internal.Trees$Template.transform(Trees.scala:518)
	at scala.reflect.internal.Trees$InternalTransformer.transform(Trees.scala:1461)
	at scala.tools.nsc.interpreter.ReplGlobal$wrapperCleanup$WrapperCleanupTransformer.transform(ReplGlobal.scala:72)
	at scala.tools.nsc.interpreter.ReplGlobal$wrapperCleanup$WrapperCleanupTransformer.transform(ReplGlobal.scala:63)
	at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2587)
	at scala.reflect.internal.Trees$ModuleDef.$anonfun$transform$3(Trees.scala:370)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2625)
	at scala.reflect.internal.Trees$ModuleDef.transform(Trees.scala:369)
	at scala.reflect.internal.Trees$InternalTransformer.transform(Trees.scala:1461)
	at scala.tools.nsc.interpreter.ReplGlobal$wrapperCleanup$WrapperCleanupTransformer.transform(ReplGlobal.scala:72)
	at scala.tools.nsc.interpreter.ReplGlobal$wrapperCleanup$WrapperCleanupTransformer.transform(ReplGlobal.scala:63)
	at scala.reflect.api.Trees$Transformer.$anonfun$transformStats$1(Trees.scala:2614)
	at scala.reflect.api.Trees$Transformer.transformStats(Trees.scala:2612)
	at scala.reflect.internal.Trees$PackageDef.$anonfun$transform$1(Trees.scala:316)
	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2625)
	at scala.reflect.internal.Trees$PackageDef.transform(Trees.scala:316)
	at scala.reflect.internal.Trees$InternalTransformer.transform(Trees.scala:1461)
	at scala.tools.nsc.interpreter.ReplGlobal$wrapperCleanup$WrapperCleanupTransformer.transform(ReplGlobal.scala:72)
	at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:162)
	at scala.tools.nsc.interpreter.ReplGlobal$wrapperCleanup$WrapperCleanupTransformer.transformUnit(ReplGlobal.scala:65)
	at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:36)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:451)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:398)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1506)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1490)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compile(IMain.scala:737)
	at scala.tools.nsc.interpreter.IMain$Request.compile(IMain.scala:949)
	at scala.tools.nsc.interpreter.IMain.compile(IMain.scala:529)
	at scala.tools.nsc.interpreter.IMain.doInterpret(IMain.scala:515)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:499)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:497)
	at scala.tools.nsc.interpreter.shell.ILoop.loop$1(ILoop.scala:868)
	at scala.tools.nsc.interpreter.shell.ILoop.interpretStartingWith(ILoop.scala:900)
	at scala.tools.nsc.interpreter.shell.ILoop.command(ILoop.scala:427)
	at scala.tools.nsc.interpreter.shell.ILoop.processLine(ILoop.scala:434)
	at scala.tools.nsc.interpreter.shell.ILoop.loop(ILoop.scala:452)
	at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:954)
	at xsbt.ConsoleInterface.run(ConsoleInterface.scala:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
	at sbt.internal.inc.AnalyzingCompiler.console(AnalyzingCompiler.scala:210)
	at sbt.Console.console0$1(Console.scala:48)
	at sbt.Console.$anonfun$apply$2(Console.scala:51)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
	at sbt.TrapExit$App.run(TrapExit.scala:257)
	at java.lang.Thread.run(Thread.java:748)

[error] (run-main-0) scala.NotImplementedError: an implementation is missing
[error] scala.NotImplementedError: an implementation is missing
[error] 	at scala.tools.nsc.interpreter.jline.Reader.readOneKey(Reader.scala:31)
[error] 	at scala.tools.nsc.interpreter.shell.InteractiveReader.readYesOrNo(InteractiveReader.scala:28)
[error] 	at scala.tools.nsc.interpreter.shell.InteractiveReader.readYesOrNo$(InteractiveReader.scala:28)
[error] 	at scala.tools.nsc.interpreter.jline.Reader.readYesOrNo(Reader.scala:28)
[error] 	at scala.tools.nsc.interpreter.shell.ILoop$$anonfun$1.fn$1(ILoop.scala:407)
[error] 	at scala.tools.nsc.interpreter.shell.ILoop$$anonfun$1.applyOrElse(ILoop.scala:410)
[error] 	at scala.tools.nsc.interpreter.shell.ILoop$$anonfun$1.applyOrElse(ILoop.scala:391)
[error] 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
[error] 	at scala.tools.nsc.interpreter.shell.ILoop.loop(ILoop.scala:452)
[error] 	at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:954)
[error] 	at xsbt.ConsoleInterface.run(ConsoleInterface.scala:78)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error] 	at sbt.internal.inc.AnalyzingCompiler.console(AnalyzingCompiler.scala:210)
[error] 	at sbt.Console.console0$1(Console.scala:48)
[error] 	at sbt.Console.$anonfun$apply$2(Console.scala:51)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:257)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Nonzero exit code: 1
```

For the session slayer see scala/bug#9910

**Comment by SethTisue** [comment]
my own favorite compiler-slayer: `trait T extends (Any{})` (https://github.com/scala/bug/issues/10548)

I attempted to implement `readOneKey` as follows:

```
+  protected def readOneKey(prompt: String): Int = {
+    print(prompt)
+    reader.getTerminal.writer.flush()
+    // ugly cast, but that's also what they do in jline.example.Example
+    reader.asInstanceOf[LineReaderImpl].readCharacter()
+  }
```

but it doesn't work, you have to press return before `readCharacter` returns

`readOneKey` is only used in this one place, so I think it would be fine to just reimplement `readYesOrNo` to be line-based, it's not worth messing with

**Comment by SethTisue** [comment]
closing on the presumption my fix will be merged

**Comment by Jasper-M** [comment]
@SethTisue Now I get

```
That entry seems to have slain the compiler.  Shall I replay
your session? I can re-run each line except the last one.
[y/n]y
replay> "foo"
[error] (run-main-0) java.lang.AssertionError: assertion failed: 
[error]   transformCaseApply: name = Any! tree = Any / class scala.reflect.internal.Trees$Ident
[error]      while compiling: <console>
[error]         during phase: refchecks
[error]      library version: version 2.13.2-bin-018d78b
[error]     compiler version: version 2.13.2-bin-018d78b
[error]   reconstructed args: -bootclasspath ******
[error] 
[error]   last tree to typer: Literal(Constant($line4.$read.type))
[error]        tree position: <unknown>
[error]             tree tpe: Class[$line4.$read.type](classOf[$line4.$read$])
[error]               symbol: null
[error]            call site: trait T in package $line4
[error] 
[error] == Source file context for tree position ==
[error] 
[error] java.lang.AssertionError: assertion failed: 
[error]   transformCaseApply: name = Any! tree = Any / class scala.reflect.internal.Trees$Ident
[error]      while compiling: <console>
[error]         during phase: refchecks
[error]      library version: version 2.13.2-bin-018d78b
[error]     compiler version: version 2.13.2-bin-018d78b
[error]   reconstructed args: -bootclasspath ******
[error] 
[error]   last tree to typer: Literal(Constant($line4.$read.type))
[error]        tree position: <unknown>
[error]             tree tpe: Class[$line4.$read.type](classOf[$line4.$read$])
[error]               symbol: null
[error]            call site: trait T in package $line4
[error] 
[error] == Source file context for tree position ==
[error] 
[error] 
[error] 	at scala.reflect.internal.SymbolTable.throwAssertionError(SymbolTable.scala:170)
[error] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1742)
[error] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:89)
[error] 	at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2583)
[error] 	at scala.reflect.internal.Trees$Template.transform(Trees.scala:518)
[error] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1769)
[error] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:89)
[error] 	at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2587)
[error] 	at scala.reflect.internal.Trees$CompoundTypeTree.transform(Trees.scala:908)
[error] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1769)
[error] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:89)
[error] 	at scala.reflect.api.Trees$Transformer.transformTrees(Trees.scala:2583)
[error] 	at scala.reflect.internal.Trees$Template.transform(Trees.scala:518)
[error] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1769)
[error] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:89)
[error] 	at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2587)
[error] 	at scala.reflect.internal.Trees$ClassDef.$anonfun$transform$2(Trees.scala:335)
[error] 	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2625)
[error] 	at scala.reflect.internal.Trees$ClassDef.transform(Trees.scala:334)
[error] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1769)
[error] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStat(RefChecks.scala:1210)
[error] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:1181)
[error] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:89)
[error] 	at scala.reflect.internal.Trees$Template.transform(Trees.scala:518)
[error] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1769)
[error] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:89)
[error] 	at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2587)
[error] 	at scala.reflect.internal.Trees$ClassDef.$anonfun$transform$2(Trees.scala:335)
[error] 	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2625)
[error] 	at scala.reflect.internal.Trees$ClassDef.transform(Trees.scala:334)
[error] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1769)
[error] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStat(RefChecks.scala:1210)
[error] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:1181)
[error] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:89)
[error] 	at scala.reflect.internal.Trees$Template.transform(Trees.scala:518)
[error] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1769)
[error] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:89)
[error] 	at scala.reflect.api.Trees$Transformer.transformTemplate(Trees.scala:2587)
[error] 	at scala.reflect.internal.Trees$ClassDef.$anonfun$transform$2(Trees.scala:335)
[error] 	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2625)
[error] 	at scala.reflect.internal.Trees$ClassDef.transform(Trees.scala:334)
[error] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1769)
[error] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStat(RefChecks.scala:1210)
[error] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:1181)
[error] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transformStats(RefChecks.scala:89)
[error] 	at scala.reflect.internal.Trees$PackageDef.$anonfun$transform$1(Trees.scala:316)
[error] 	at scala.reflect.api.Trees$Transformer.atOwner(Trees.scala:2625)
[error] 	at scala.reflect.internal.Trees$PackageDef.transform(Trees.scala:316)
[error] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1769)
[error] 	at scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:162)
[error] 	at scala.tools.nsc.transform.Transform$Phase.apply(Transform.scala:36)
[error] 	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:451)
[error] 	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:398)
[error] 	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1505)
[error] 	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1489)
[error] 	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.compile(IMain.scala:741)
[error] 	at scala.tools.nsc.interpreter.IMain$Request.compile(IMain.scala:953)
[error] 	at scala.tools.nsc.interpreter.IMain.compile(IMain.scala:533)
[error] 	at scala.tools.nsc.interpreter.IMain.doInterpret(IMain.scala:519)
[error] 	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:503)
[error] 	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:501)
[error] 	at scala.tools.nsc.interpreter.shell.ILoop.loop$1(ILoop.scala:874)
[error] 	at scala.tools.nsc.interpreter.shell.ILoop.interpretStartingWith(ILoop.scala:906)
[error] 	at scala.tools.nsc.interpreter.shell.ILoop.command(ILoop.scala:431)
[error] 	at scala.tools.nsc.interpreter.shell.ILoop.$anonfun$replay$2(ILoop.scala:502)
[error] 	at scala.tools.nsc.interpreter.shell.ILoop.$anonfun$replay$1(ILoop.scala:500)
[error] 	at scala.tools.nsc.interpreter.shell.ReplReporterImpl.indenting(Reporter.scala:51)
[error] 	at scala.tools.nsc.interpreter.shell.ILoop.replay(ILoop.scala:500)
[error] 	at scala.tools.nsc.interpreter.shell.ILoop$$anonfun$1.applyOrElse(ILoop.scala:414)
[error] 	at scala.tools.nsc.interpreter.shell.ILoop$$anonfun$1.applyOrElse(ILoop.scala:395)
[error] 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:35)
[error] 	at scala.tools.nsc.interpreter.shell.ILoop.loop(ILoop.scala:456)
[error] 	at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:960)
[error] 	at xsbt.ConsoleInterface.run(ConsoleInterface.scala:78)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] 	at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error] 	at sbt.internal.inc.AnalyzingCompiler.console(AnalyzingCompiler.scala:210)
[error] 	at sbt.Console.console0$1(Console.scala:48)
[error] 	at sbt.Console.$anonfun$apply$2(Console.scala:51)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:257)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Nonzero exit code: 1
[error] (Compile / consoleQuick) Nonzero exit code: 1
[error] Total time: 11 s, completed Apr 7, 2020 9:53:12 AM
```

**Comment by SethTisue** [comment]
@Jasper-M is there still a JLine issue here? if so, can you be more specific about what it is? hope I'm not being dense

or is whatever remains here already covered by https://github.com/scala/bug/issues/9910 ?

**Comment by Jasper-M** [comment]
Now (8 days ago) the prompt appears and when I say 'y' it does seem to replay the session but then the REPL crashes anyway, with what appears to be the original AssertionError.

I picked your compiler slayer by the way: `trait T extends (Any{})`. I think mine got fixed.

**Comment by Jasper-M** [comment]
@SethTisue Update.
When I answer 'y' it crashes. 
When I answer 'n' it doesn't crash but it doesn't seem to abandon the session either. But apparently that's also what 2.13.1 does for 'n'. Maybe I just don't understand what "replay session" and "abandoning crashed session" mean...

```
scala> val foo = "bar"
val foo: String = bar

scala> +:.o=0
          ^
       error: value o is not a member of object collection.+:
java.lang.NullPointerException
	at scala.tools.nsc.typechecker.Typers$Typer.shadowsSetter$1(Typers.scala:4696)

That entry seems to have slain the compiler.  Shall I replay
your session? I can re-run each line except the last one.
[y/n]n

Abandoning crashed session.

scala> foo
val res0: String = bar
```
