### ISSUE TITLE
Get our test suite working on Java 15

### ISSUE THREAD

**Issue by dwijnand** [scala/scala-dev#745]
Younger sibling to #581.

I ran it (`testAll`) and got the following errors:

```
[error] Test scala.collection.immutable.IntMapTest.isEmpty$u0020O$u00281$u0029 failed: java.lang.NoSuchFieldException: modifiers, took 0.009 sec
[error]     at java.lang.Class.getDeclaredField(Class.java:2569)
[error]     at scala.tools.testkit.ReflectUtil$.modsField$lzycompute(ReflectUtil.scala:25)
[error]     at scala.tools.testkit.ReflectUtil$.modsField(ReflectUtil.scala:25)
[error]     at scala.tools.testkit.ReflectUtil$.$anonfun$getFieldAccessible$1(ReflectUtil.scala:32)
[error]     at scala.tools.testkit.ReflectUtil$.$anonfun$getFieldAccessible$1$adapted(ReflectUtil.scala:30)
[error]     at scala.util.ChainingOps$.tap$extension(ChainingOps.scala:40)
[error]     at scala.tools.testkit.ReflectUtil$.getFieldAccessible(ReflectUtil.scala:30)
[error]     at scala.collection.immutable.IntMapTest.isEmpty$u0020O$u00281$u0029(IntMapTest.scala:27)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
[error]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:564)
[error]     ...
[error] Test scala.collection.immutable.LongMapTest.isEmpty$u0020O$u00281$u0029 failed: java.lang.NoSuchFieldException: modifiers, took 0.005 sec
[error]     at java.lang.Class.getDeclaredField(Class.java:2569)
[error]     at scala.tools.testkit.ReflectUtil$.modsField$lzycompute(ReflectUtil.scala:25)
[error]     at scala.tools.testkit.ReflectUtil$.modsField(ReflectUtil.scala:25)
[error]     at scala.tools.testkit.ReflectUtil$.$anonfun$getFieldAccessible$1(ReflectUtil.scala:32)
[error]     at scala.tools.testkit.ReflectUtil$.$anonfun$getFieldAccessible$1$adapted(ReflectUtil.scala:30)
[error]     at scala.util.ChainingOps$.tap$extension(ChainingOps.scala:40)
[error]     at scala.tools.testkit.ReflectUtil$.getFieldAccessible(ReflectUtil.scala:30)
[error]     at scala.collection.immutable.LongMapTest.isEmpty$u0020O$u00281$u0029(LongMapTest.scala:28)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
[error]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:564)
[error]     ...
```

```
!!    1 - run/reflection-magicsymbols-invoke.scala  [output differs]
!!    2 - run/repl-trim-stack-trace.scala           [output differs]
!!    3 - run/stream-gc.scala                       [non-zero exit code]
!!    4 - run/t6344.scala                           [output differs]
!!    5 - run/t9529                                 [output differs]
```

```
!!    1 - neg/macro-invalidret                      [output differs]
```

```
!!  1 - jvm/t8786-sig.scala                       [output differs]
```

```
!!  1 - presentation/infix-completion             [output differs]
!!  2 - presentation/infix-completion2            [output differs]
```

**Comment by dwijnand** [comment]
scala/scala#9324 did a bunch of fixes.  We don't have it tested in CI continuously though.  Perhaps we have spare capacity on travis-ci.com to run the suite nightly on JDK 15.  Or weekly.

**Comment by SethTisue** [comment]
Consolidating under #522. (If the tests pass on 16, they will likely pass on 11 as well.)
