### ISSUE TITLE
core repos failing in JDK 17 build, related to lambda deserialization

### ISSUE THREAD

**Issue by SethTisue** [scala/scala-dev#779]
and it only fails in 2.12.x, not 2.13.x

sample stack trace: https://gist.github.com/SethTisue/7d3f147f5061bae1978a73868f1941a2

```
[scalacheck:error] Caused by: java.lang.IllegalArgumentException: too many arguments
[scalacheck:error] 	at java.base/java.lang.invoke.LambdaMetafactory.altMetafactory(LambdaMetafactory.java:511)
[scalacheck:error] 	at scala.runtime.LambdaDeserializer$.makeCallSite$1(LambdaDeserializer.scala:105)
```

@retronym I haven't really dug into this yet, but before I even start digging, does this ring any obvious bells...?

**Comment by SethTisue** [comment]
I've transferred this to scala-dev now that we know it isn't a community build phantom. Perhaps we'll transfer it again, to scala/bug :-)

**Comment by retronym** [comment]
Spotted the problem, mea culpa.
