### ISSUE TITLE
still some concurrency issue in scripted tests

### ISSUE THREAD

**Issue by lrytz** [scala/scala-dev#882]
Failure in a merge commit test run on GitHub https://github.com/scala/scala/actions/runs/11819553129/job/32929735138 (windows 21)

```
2024-11-13T15:30:37.5870241Z [info] Running source-dependencies/malformed-class-name
2024-11-13T15:30:37.5871506Z [info] Running apiinfo/circular-structure
2024-11-13T15:30:54.0980457Z sbt.internal.scripted.TestException: {line -1}  Reload for scripted batch execution failed.
2024-11-13T15:30:54.1715031Z [error] [info] waiting for lock on D:\a\scala\scala\target\sbtTest\.sbt-scripted\sbt.boot.lock to be available...
2024-11-13T15:30:54.1716753Z 	at sbt.scriptedtest.ScriptedTests.$anonfun$runBatchedTests$5(ScriptedTests.scala:237)
2024-11-13T15:30:54.1718153Z 	at sbt.scriptedtest.ScriptedTests.$anonfun$runBatchedTests$5$adapted(ScriptedTests.scala:231)
2024-11-13T15:30:54.1719518Z 	at sbt.scriptedtest.ScriptedTests.$anonfun$commonRunTest$6(ScriptedTests.scala:321)
2024-11-13T15:30:54.1720664Z 	at scala.util.control.Exception$Catch.apply(Exception.scala:228)
2024-11-13T15:30:54.1721752Z 	at sbt.scriptedtest.ScriptedTests.commonRunTest(ScriptedTests.scala:320)
2024-11-13T15:30:54.1723015Z 	at sbt.scriptedtest.ScriptedTests.$anonfun$runBatchedTests$3(ScriptedTests.scala:241)
2024-11-13T15:30:54.1724331Z 	at sbt.scriptedtest.ScriptedTests.runOrHandleDisabled(ScriptedTests.scala:272)
2024-11-13T15:30:54.1726026Z 	at sbt.scriptedtest.ScriptedTests.$anonfun$runBatchedTests$1(ScriptedTests.scala:245)
2024-11-13T15:30:54.1727297Z 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
2024-11-13T15:30:54.1728405Z 	at scala.collection.mutable.ArraySeq.foreach(ArraySeq.scala:75)
2024-11-13T15:30:54.1729436Z 	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
2024-11-13T15:30:54.1730494Z 	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
2024-11-13T15:30:54.1731556Z 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
2024-11-13T15:30:54.1732684Z 	at sbt.scriptedtest.ScriptedTests.runBatchTests$1(ScriptedTests.scala:217)
2024-11-13T15:30:54.1733894Z 	at sbt.scriptedtest.ScriptedTests.runBatchedTests(ScriptedTests.scala:261)
2024-11-13T15:30:54.1735597Z 	at sbt.scriptedtest.ScriptedTests.$anonfun$batchScriptedRunner$11(ScriptedTests.scala:156)
2024-11-13T15:30:54.1736727Z 	at sbt.io.IO$.withTemporaryDirectory(IO.scala:496)
2024-11-13T15:30:54.1737494Z 	at sbt.io.IO$.withTemporaryDirectory(IO.scala:506)
2024-11-13T15:30:54.1738599Z 	at sbt.scriptedtest.ScriptedTests.$anonfun$batchScriptedRunner$10(ScriptedTests.scala:156)
2024-11-13T15:30:54.1739898Z 	at sbt.scriptedtest.ScriptedRunner.$anonfun$runAll$3(ScriptedTests.scala:634)
2024-11-13T15:30:54.1741334Z 	at scala.collection.parallel.mutable.ParArray$ParArrayIterator.flatmap2combiner(ParArray.scala:419)
2024-11-13T15:30:54.1742843Z 	at scala.collection.parallel.ParIterableLike$FlatMap.leaf(ParIterableLike.scala:1082)
2024-11-13T15:30:54.1744078Z 	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
2024-11-13T15:30:54.1745334Z 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
2024-11-13T15:30:54.1746387Z 	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
2024-11-13T15:30:54.1747365Z 	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
2024-11-13T15:30:54.1748302Z 	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
2024-11-13T15:30:54.1749512Z 	at scala.collection.parallel.ParIterableLike$FlatMap.tryLeaf(ParIterableLike.scala:1078)
2024-11-13T15:30:54.1751037Z 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal(Tasks.scala:160)
2024-11-13T15:30:54.1752565Z 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.internal$(Tasks.scala:157)
2024-11-13T15:30:54.1754177Z 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:440)
2024-11-13T15:30:54.1755952Z 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:150)
2024-11-13T15:30:54.1757466Z 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
2024-11-13T15:30:54.1759111Z 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
2024-11-13T15:30:54.1760607Z 	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
2024-11-13T15:30:54.1762094Z 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
2024-11-13T15:30:54.1763492Z 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.tryRemoveAndExec(ForkJoinPool.java:1351)
2024-11-13T15:30:54.1765140Z 	at java.base/java.util.concurrent.ForkJoinTask.awaitDone(ForkJoinTask.java:422)
2024-11-13T15:30:54.1766430Z 	at java.base/java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:651)
2024-11-13T15:30:54.1767638Z 	at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync(Tasks.scala:379)
2024-11-13T15:30:54.1768881Z 	at scala.collection.parallel.ForkJoinTasks$WrappedTask.sync$(Tasks.scala:379)
2024-11-13T15:30:54.1770317Z 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.sync(Tasks.scala:440)
2024-11-13T15:30:54.1771838Z 	at scala.collection.parallel.ForkJoinTasks.executeAndWaitResult(Tasks.scala:423)
2024-11-13T15:30:54.1773221Z 	at scala.collection.parallel.ForkJoinTasks.executeAndWaitResult$(Tasks.scala:416)
2024-11-13T15:30:54.1774837Z 	at scala.collection.parallel.ForkJoinTaskSupport.executeAndWaitResult(TaskSupport.scala:60)
2024-11-13T15:30:54.1776386Z 	at scala.collection.parallel.ParIterableLike$ResultMapping.leaf(ParIterableLike.scala:968)
2024-11-13T15:30:54.1777653Z 	at scala.collection.parallel.Task.$anonfun$tryLeaf$1(Tasks.scala:53)
2024-11-13T15:30:54.1778757Z 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
2024-11-13T15:30:54.1779793Z 	at scala.util.control.Breaks$$anon$1.catchBreak(Breaks.scala:67)
2024-11-13T15:30:54.1780714Z 	at scala.collection.parallel.Task.tryLeaf(Tasks.scala:56)
2024-11-13T15:30:54.1781628Z 	at scala.collection.parallel.Task.tryLeaf$(Tasks.scala:50)
2024-11-13T15:30:54.1782913Z 	at scala.collection.parallel.ParIterableLike$ResultMapping.tryLeaf(ParIterableLike.scala:963)
2024-11-13T15:30:54.1784916Z 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute(Tasks.scala:153)
2024-11-13T15:30:54.1786664Z 	at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask.compute$(Tasks.scala:149)
2024-11-13T15:30:54.1788462Z 	at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:440)
2024-11-13T15:30:54.1790074Z 	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
2024-11-13T15:30:54.1791310Z 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)
2024-11-13T15:30:54.1792659Z 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)
2024-11-13T15:30:54.1793995Z 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)
2024-11-13T15:30:54.1795392Z 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)
2024-11-13T15:30:54.1796774Z 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)
2024-11-13T15:30:54.1798585Z Caused by: sbt.internal.scripted.TestException: {line -1}  Command failed: Remote sbt initialization failed
2024-11-13T15:30:54.1800097Z 	at sbt.scriptedtest.BatchScriptRunner.processStatement(BatchScriptRunner.scala:54)
2024-11-13T15:30:54.1801454Z 	at sbt.scriptedtest.ScriptedTests.$anonfun$runBatchedTests$5(ScriptedTests.scala:233)
2024-11-13T15:30:54.1802362Z 	... 60 more
2024-11-13T15:30:54.1803013Z [info] sbt thinks that server is already booting because of this exception:
2024-11-13T15:30:54.1805048Z [error] sbt.internal.ServerAlreadyBootingException: java.io.IOException: Could not create lock for \\.\pipe\sbt-load-7218651322503748788_lock, error 1336
2024-11-13T15:30:54.1806831Z [error] 	at sbt.internal.BootServerSocket.newSocket(BootServerSocket.java:357)
2024-11-13T15:30:54.1807988Z [error] 	at sbt.internal.BootServerSocket.<init>(BootServerSocket.java:296)
2024-11-13T15:30:54.1808933Z [error] 	at sbt.xMain$.getSocketOrExit(Main.scala:153)
2024-11-13T15:30:54.1809798Z [error] 	at sbt.xMain$.bootServerSocket$lzycompute$1(Main.scala:79)
2024-11-13T15:30:54.1810680Z [error] 	at sbt.xMain$.bootServerSocket$1(Main.scala:79)
2024-11-13T15:30:54.1811601Z [error] 	at sbt.xMain$.withStreams$1(Main.scala:87)
2024-11-13T15:30:54.1812267Z [error] 	at sbt.xMain$.run(Main.scala:124)
2024-11-13T15:30:54.1813502Z [error] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
2024-11-13T15:30:54.1815068Z [error] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
2024-11-13T15:30:54.1816170Z [error] 	at sbt.internal.XMainConfiguration.run(XMainConfiguration.java:59)
2024-11-13T15:30:54.1817051Z [error] 	at sbt.xMain.run(Main.scala:48)
2024-11-13T15:30:54.1817775Z [error] 	at xsbt.boot.Launch$.$anonfun$run$1(Launch.scala:149)
2024-11-13T15:30:54.1818688Z [error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:176)
2024-11-13T15:30:54.1819517Z [error] 	at xsbt.boot.Launch$.run(Launch.scala:149)
2024-11-13T15:30:54.1820326Z [error] 	at xsbt.boot.Launch$.$anonfun$apply$1(Launch.scala:44)
2024-11-13T15:30:54.1821152Z [error] 	at xsbt.boot.Launch$.launch(Launch.scala:159)
2024-11-13T15:30:54.1821912Z [error] 	at xsbt.boot.Launch$.apply(Launch.scala:44)
2024-11-13T15:30:54.1822641Z [error] 	at xsbt.boot.Launch$.apply(Launch.scala:21)
2024-11-13T15:30:54.1823354Z [error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:78)
2024-11-13T15:30:54.1824041Z [error] 	at xsbt.boot.Boot$.run(Boot.scala:73)
2024-11-13T15:30:54.1824806Z [error] 	at xsbt.boot.Boot$.main(Boot.scala:21)
2024-11-13T15:30:54.1825467Z [error] 	at xsbt.boot.Boot.main(Boot.scala)
2024-11-13T15:30:54.1826837Z [error] Caused by: java.io.IOException: Could not create lock for \\.\pipe\sbt-load-7218651322503748788_lock, error 1336
2024-11-13T15:30:54.1828574Z [error] 	at org.scalasbt.ipcsocket.Win32NamedPipeServerSocket.<init>(Win32NamedPipeServerSocket.java:129)
2024-11-13T15:30:54.1830425Z [error] 	at org.scalasbt.ipcsocket.Win32NamedPipeServerSocket.<init>(Win32NamedPipeServerSocket.java:48)
2024-11-13T15:30:54.1831877Z [error] 	at sbt.internal.BootServerSocket.newSocket(BootServerSocket.java:351)
2024-11-13T15:30:54.1832747Z [error] 	... 21 more
2024-11-13T15:30:54.1833200Z [info] [0J
2024-11-13T15:30:54.1833679Z [error] x apiinfo/circular-structure 
2024-11-13T15:30:54.3249933Z [info] Running apiinfo/java-basic
2024-11-13T15:31:41.6454050Z [info] Running source-dependencies/malformed-class-name-with-dollar
```

**Comment by lrytz** [comment]
rerun passed

**Comment by lrytz** [comment]
Another `scripted` failure, on Ubuntu / Java 21.0.5. Looks different than above though.

  - Above: `Remote sbt initialization failed` / `ServerAlreadyBootingException: java.io.IOException: Could not create lock for \\.\pipe\sbt-load-7218651322503748788_lock`
  - This time: `Could not create file /tmp/sbt_e8bb30a1/pro/target/streams/_global/cleanIvy/_global/streams/out java.io.IOException: No such file or directory`

```
[info] [info] welcome to sbt 1.10.7 (Eclipse Adoptium Java 21.0.5)
[info] [info] loading project definition from /tmp/sbt_e8bb30a1/project
[info] [info] compiling 1 Scala source to /tmp/sbt_e8bb30a1/project/target/scala-2.12/sbt-1.0/classes ...
[info] [info] done compiling
[info] [info] loading settings for project sbt_e8bb30a1 from build.sbt...
[info] [info] set current project to sbt_e8bb30a1 (in build file:/tmp/sbt_e8bb30a1/)
[info] [success] Total time: 0 s, completed Jan 21, 2025, 1:55:27 PM
[info] [info] welcome to sbt 1.10.7 (Eclipse Adoptium Java 21.0.5)
[info] [info] loading project definition from /tmp/sbt_e8bb30a1/project
[info] [info] loading settings for project pro from common.sbt...
[info] [info] loading settings for project sbt_e8bb30a1 from build.sbt, common.sbt...
[info] [info] set current project to sbt_e8bb30a1 (in build file:/tmp/sbt_e8bb30a1/)
[info] [error] Could not create file /tmp/sbt_e8bb30a1/pro/target/streams/_global/cleanIvy/_global/streams/outjava.io.IOException: No such file or directory
[info] [error] 	at sbt.internal.io.ErrorHandling$.translate(ErrorHandling.scala:21)
[info] [error] 	at sbt.io.IO$.$anonfun$touch$2(IO.scala:313)
[info] [error] 	at sbt.internal.io.Retry$.apply$mVc$sp(Retry.scala:47)
[info] [error] 	at sbt.internal.io.Retry$.apply$mVc$sp(Retry.scala:29)
[info] [error] 	at sbt.internal.io.Retry$.apply$mVc$sp(Retry.scala:24)
[info] [error] 	at sbt.io.IO$.touch(IO.scala:310)
[info] [error] 	at sbt.std.Streams$$anon$2$$anon$3.make(Streams.scala:211)
[info] [error] 	at sbt.std.Streams$$anon$2$$anon$3.text(Streams.scala:178)
[info] [error] 	at sbt.std.Streams$$anon$2$$anon$3.log(Streams.scala:199)
[info] [error] 	at sbt.std.TaskStreams.log(Streams.scala:72)
[info] [error] 	at sbt.std.TaskStreams.log$(Streams.scala:72)
[info] [error] 	at sbt.std.Streams$$anon$2$$anon$3.log$lzycompute(Streams.scala:158)
[info] [error] 	at sbt.std.Streams$$anon$2$$anon$3.log(Streams.scala:158)
[info] [error] 	at sbt.Defaults$.$anonfun$compileBase$8(Defaults.scala:713)
[info] [error] 	at sbt.Defaults$.$anonfun$compileBase$8$adapted(Defaults.scala:713)
[info] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[info] [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[info] [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[info] [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[info] [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[info] [error] 	at sbt.Execute.work(Execute.scala:292)
[info] [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[info] [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[info] [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[info] [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[info] [error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[info] [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[info] [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[info] [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[info] [error] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[info] [error] Caused by: java.io.IOException: No such file or directory
[info] [error] 	at java.base/java.io.UnixFileSystem.createFileExclusively0(Native Method)
[info] [error] 	at java.base/java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:258)
[info] [error] 	at java.base/java.io.File.createNewFile(File.java:1045)
[info] [error] 	at sbt.io.IO$.$anonfun$touch$4(IO.scala:313)
[info] [error] 	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
[info] [error] 	at sbt.internal.io.ErrorHandling$.translate(ErrorHandling.scala:19)
[info] [error] 	at sbt.io.IO$.$anonfun$touch$2(IO.scala:313)
[info] [error] 	at sbt.internal.io.Retry$.apply$mVc$sp(Retry.scala:47)
[info] [error] 	at sbt.internal.io.Retry$.apply$mVc$sp(Retry.scala:29)
[info] [error] 	at sbt.internal.io.Retry$.apply$mVc$sp(Retry.scala:24)
[info] [error] 	at sbt.io.IO$.touch(IO.scala:310)
[info] [error] 	at sbt.std.Streams$$anon$2$$anon$3.make(Streams.scala:211)
[info] [error] 	at sbt.std.Streams$$anon$2$$anon$3.text(Streams.scala:178)
[info] [error] 	at sbt.std.Streams$$anon$2$$anon$3.log(Streams.scala:199)
[info] [error] 	at sbt.std.TaskStreams.log(Streams.scala:72)
[info] [error] 	at sbt.std.TaskStreams.log$(Streams.scala:72)
[info] [error] 	at sbt.std.Streams$$anon$2$$anon$3.log$lzycompute(Streams.scala:158)
[info] [error] 	at sbt.std.Streams$$anon$2$$anon$3.log(Streams.scala:158)
[info] [error] 	at sbt.Defaults$.$anonfun$compileBase$8(Defaults.scala:713)
[info] [error] 	at sbt.Defaults$.$anonfun$compileBase$8$adapted(Defaults.scala:713)
[info] [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[info] [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:63)
[info] [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:69)
[info] [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:283)
[info] [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:24)
[info] [error] 	at sbt.Execute.work(Execute.scala:292)
[info] [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:283)
[info] [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[info] [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:65)
[info] [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[info] [error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
[info] [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
[info] [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[info] [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[info] [error] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[info] [error] (pro / cleanIvy) Could not create file /tmp/sbt_e8bb30a1/pro/target/streams/_global/cleanIvy/_global/streams/outjava.io.IOException: No such file or directory
[info] [error] Total time: 0 s, completed Jan 21, 2025, 1:55:29 PM
Error:  x source-dependencies/trait-local-change 
Error:   Cause of test exception: {line 3}  Command failed: pro/clean failed
```

**Comment by lrytz** [comment]
Another exception this time on windows+jdk21, and same a day later on windows+jdk23

- `[info] [error] (macro-provider / cleanIvy) Could not create file C:\Users\runneradmin\AppData\Local\Temp\sbt_31fb80b\macro-provider\target\streams\_global\cleanIvy\_global\streams\outjava.io.IOException: Access is denied
[info] [error] Total time: 0 s, completed Jan 30, 2025, 8:13:39 AM`

```
[info] [error] Could not create file C:\Users\runneradmin\AppData\Local\Temp\sbt_31fb80b\macro-provider\target\streams\_global\cleanIvy\_global\streams\outjava.io.IOException: Access is denied
[info] [error] 	at sbt.internal.io.ErrorHandling$.translate(ErrorHandling.scala:21)
[info] [error] 	at sbt.io.IO$.$anonfun$touch$2(IO.scala:313)
[info] [error] 	at sbt.internal.io.Retry$.apply$mVc$sp(Retry.scala:47)
[info] [error] 	at sbt.internal.io.Retry$.apply$mVc$sp(Retry.scala:29)
[info] [error] 	at sbt.internal.io.Retry$.apply$mVc$sp(Retry.scala:24)
[info] [error] 	at sbt.io.IO$.touch(IO.scala:310)
[info] [error] 	at sbt.std.Streams$$anon$2$$anon$3.make(Streams.scala:211)
[info] [error] 	at sbt.std.Streams$$anon$2$$anon$3.text(Streams.scala:178)
[info] [error] 	at sbt.std.Streams$$anon$2$$anon$3.log(Streams.scala:199)
[info] [error] 	at sbt.std.TaskStreams.log(Streams.scala:72)
[info] [error] 	at sbt.std.TaskStreams.log$(Streams.scala:72)
[info] [error] 	at sbt.std.Streams$$anon$2$$anon$3.log$lzycompute(Streams.scala:158)
[info] [error] 	at sbt.std.Streams$$anon$2$$anon$3.log(Streams.scala:158)
[info] [error] 	at sbt.Defaults$.$anonfun$compileBase$8(Defaults.scala:713)
```
